export type FranchiseFetchType = "collection" | "keyword" | "tv" | "search";
export type FranchiseGenre =
  | "superherois"
  | "acao"
  | "scifi"
  | "fantasia"
  | "terror"
  | "drama"
  | "animacao"
  | "anime";
export type FranchiseCategory = "filmes" | "series" | "anime";

export interface ChronologicalItem {
  tmdbId: number;
  type: "movie" | "tv";
  label: string;
  note?: string;
}

export interface Franchise {
  id: string;
  name: string;
  shortName: string;
  tagline: string;
  description: string;
  color: string;
  accentColor: string;
  bgGradient: [string, string, string];
  category: FranchiseCategory;
  genre: FranchiseGenre;
  fetchType: FranchiseFetchType;
  tmdbCollectionId?: number;
  tmdbKeywordId?: number;
  tmdbTvId?: number;
  relatedTvIds?: number[];
  searchQuery?: string;
  searchType?: "movie" | "tv";
  yearRange: string;
  contentCount: number;
  totalHours: number;
  bannerFeatured?: boolean;
  isTop10?: boolean;
  related: string[];
  chronologicalContent?: ChronologicalItem[];
}

export const FRANCHISES: Franchise[] = [
  // ════════════════════════════════════════
  //  SUPER-HERÓIS
  // ════════════════════════════════════════
  {
    id: "marvel",
    name: "Marvel Studios",
    shortName: "Marvel",
    tagline: "Universo Cinematográfico Marvel",
    description:
      "Todos os filmes e séries do MCU — de Homem de Ferro a Vingadores, mais de 35 títulos interconectados em cinco Fases.",
    color: "#E23636",
    accentColor: "#FF4444",
    bgGradient: ["#1a0000", "#140a0a", "#0a0000"],
    category: "filmes",
    genre: "superherois",
    fetchType: "keyword",
    tmdbKeywordId: 180547,
    yearRange: "2008 - Atual",
    contentCount: 35,
    totalHours: 120,
    bannerFeatured: true,
    isTop10: true,
    related: ["dc", "xmen", "theboys"],
  },
  {
    id: "dc",
    name: "DC Universe",
    shortName: "DC",
    tagline: "DC Extended Universe",
    description:
      "Batman, Superman, Mulher-Maravilha e a Liga da Justiça protegem o mundo num universo épico de super-heróis.",
    color: "#0064FF",
    accentColor: "#4488FF",
    bgGradient: ["#000520", "#000a30", "#00031a"],
    category: "filmes",
    genre: "superherois",
    fetchType: "keyword",
    tmdbKeywordId: 310222,
    yearRange: "2013 - Atual",
    contentCount: 22,
    totalHours: 75,
    bannerFeatured: true,
    isTop10: true,
    related: ["marvel", "xmen"],
  },
  {
    id: "xmen",
    name: "X-Men",
    shortName: "X-Men",
    tagline: "Mutantes que defendem um mundo que os odeia",
    description:
      "A saga completa dos mutantes da Marvel — da escola do Professor Xavier ao confronto com Magneto.",
    color: "#FFD700",
    accentColor: "#FFEE44",
    bgGradient: ["#1a1200", "#151000", "#0a0800"],
    category: "filmes",
    genre: "superherois",
    fetchType: "collection",
    tmdbCollectionId: 748,
    yearRange: "2000 - Atual",
    contentCount: 13,
    totalHours: 27,
    related: ["marvel", "dc"],
  },
  {
    id: "spiderman",
    name: "Spider-Man",
    shortName: "Spider-Man",
    tagline: "Com grandes poderes vêm grandes responsabilidades",
    description:
      "Peter Parker, o Homem-Aranha mais amado do cinema. Da trilogia Raimi ao MCU, passando pelo Aranhaverso.",
    color: "#E01020",
    accentColor: "#FF2233",
    bgGradient: ["#1a0002", "#150003", "#0a0001"],
    category: "filmes",
    genre: "superherois",
    fetchType: "collection",
    tmdbCollectionId: 531241,
    relatedTvIds: [],
    yearRange: "2002 - Atual",
    contentCount: 9,
    totalHours: 20,
    isTop10: true,
    related: ["marvel", "dc"],
  },
  {
    id: "batman",
    name: "Batman",
    shortName: "Batman",
    tagline: "I am the night",
    description:
      "O Cavaleiro das Trevas em todas as suas versões — de Tim Burton a Nolan. O super-herói mais sombrio de Gotham.",
    color: "#1A1A2E",
    accentColor: "#AAAAFF",
    bgGradient: ["#050508", "#080810", "#030305"],
    category: "filmes",
    genre: "superherois",
    fetchType: "collection",
    tmdbCollectionId: 263,
    yearRange: "1989 - Atual",
    contentCount: 10,
    totalHours: 22,
    related: ["dc", "marvel"],
  },
  {
    id: "deadpool",
    name: "Deadpool",
    shortName: "Deadpool",
    tagline: "O mercenário tagarela",
    description:
      "Wade Wilson, o anti-herói mais irreverente da Marvel, quebrando a quarta parede e os vilões.",
    color: "#CC0000",
    accentColor: "#FF2222",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "filmes",
    genre: "superherois",
    fetchType: "collection",
    tmdbCollectionId: 448150,
    yearRange: "2016 - Atual",
    contentCount: 3,
    totalHours: 7,
    related: ["marvel", "xmen"],
  },
  {
    id: "theboys",
    name: "The Boys",
    shortName: "The Boys",
    tagline: "Super-heróis corrompidos pelo poder",
    description:
      "E se super-heróis fossem vilões? Billy Butcher e sua equipe enfrentam os Supes, o grupo de super-heróis mais perigoso.",
    color: "#FF4500",
    accentColor: "#FF6600",
    bgGradient: ["#150500", "#180600", "#0a0300"],
    category: "series",
    genre: "superherois",
    fetchType: "tv",
    tmdbTvId: 76479,
    relatedTvIds: [138511],
    yearRange: "2019 - Atual",
    contentCount: 5,
    totalHours: 45,
    bannerFeatured: true,
    isTop10: true,
    related: ["marvel", "strangerthings"],
  },
  {
    id: "invincible",
    name: "Invincible",
    shortName: "Invincible",
    tagline: "É mais complicado do que parece",
    description:
      "Mark Grayson herda os poderes do pai, o maior super-herói da Terra. Mas o preço é mais alto do que imagina.",
    color: "#FF6600",
    accentColor: "#FF8822",
    bgGradient: ["#150500", "#1a0700", "#0a0300"],
    category: "series",
    genre: "superherois",
    fetchType: "tv",
    tmdbTvId: 95557,
    yearRange: "2021 - Atual",
    contentCount: 2,
    totalHours: 16,
    related: ["theboys", "marvel"],
  },

  // ════════════════════════════════════════
  //  AÇÃO & AVENTURA
  // ════════════════════════════════════════
  {
    id: "fastandfurious",
    name: "Velozes & Furiosos",
    shortName: "Velozes",
    tagline: "Família acima de tudo",
    description:
      "De corridas de rua ao espaço, Dom Toretto e sua família não têm limites. A franquia mais veloz do cinema.",
    color: "#FF4500",
    accentColor: "#FF6347",
    bgGradient: ["#150500", "#1a0800", "#0a0300"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 9485,
    yearRange: "2001 - Atual",
    contentCount: 11,
    totalHours: 22,
    bannerFeatured: true,
    related: ["johnwick", "missionimpossible"],
  },
  {
    id: "missionimpossible",
    name: "Missão Impossível",
    shortName: "M:I",
    tagline: "Esta mensagem se autodestruirá",
    description:
      "Ethan Hunt e o IMF em missões aparentemente impossíveis ao redor do mundo.",
    color: "#DC143C",
    accentColor: "#FF1744",
    bgGradient: ["#150008", "#1a000a", "#0a0005"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 87359,
    yearRange: "1996 - Atual",
    contentCount: 8,
    totalHours: 16,
    related: ["johnwick", "fastandfurious"],
  },
  {
    id: "johnwick",
    name: "John Wick",
    shortName: "John Wick",
    tagline: "Ele voltou por um motivo",
    description:
      "O assassino mais letal do mundo. Quatro filmes de ação coreografada que revolucionaram o gênero.",
    color: "#FFD700",
    accentColor: "#FFA500",
    bgGradient: ["#0a0800", "#100e00", "#060500"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 404609,
    yearRange: "2014 - Atual",
    contentCount: 4,
    totalHours: 8,
    related: ["missionimpossible", "fastandfurious"],
  },
  {
    id: "jamesbond",
    name: "James Bond",
    shortName: "007",
    tagline: "Bond. James Bond.",
    description:
      "O agente secreto mais famoso do mundo. 25 filmes de espionagem, gadgets e aventuras ao redor do globo.",
    color: "#C0A000",
    accentColor: "#E8C000",
    bgGradient: ["#100d00", "#150f00", "#080700"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 645,
    yearRange: "1962 - Atual",
    contentCount: 25,
    totalHours: 50,
    isTop10: true,
    related: ["missionimpossible", "johnwick"],
  },
  {
    id: "piratesofthecaribbean",
    name: "Piratas do Caribe",
    shortName: "Piratas",
    tagline: "Por que é o rum que acaba?",
    description:
      "Jack Sparrow navega os sete mares em busca de aventuras, tesouros e rum. A saga pirata mais épica do cinema.",
    color: "#8B6914",
    accentColor: "#C4952A",
    bgGradient: ["#0d0900", "#120c00", "#080600"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 295130,
    yearRange: "2003 - Atual",
    contentCount: 5,
    totalHours: 11,
    related: ["indianajones", "johnwick"],
  },
  {
    id: "indianajones",
    name: "Indiana Jones",
    shortName: "Indiana Jones",
    tagline: "O maior arqueólogo-aventureiro",
    description:
      "Dr. Henry Jones Jr. e suas aventuras arqueológicas ao redor do mundo em busca de artefatos lendários.",
    color: "#C8A96E",
    accentColor: "#E8C97E",
    bgGradient: ["#100c04", "#150f06", "#0a0803"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 84,
    yearRange: "1981 - 2023",
    contentCount: 5,
    totalHours: 11,
    related: ["fastandfurious", "missionimpossible"],
  },
  {
    id: "hungergames",
    name: "Jogos Vorazes",
    shortName: "Hunger Games",
    tagline: "Que os jogos comecem",
    description:
      "Katniss Everdeen lidera a revolução contra o Capitólio. A distopia mais poderosa do cinema.",
    color: "#FF8C00",
    accentColor: "#FFA500",
    bgGradient: ["#150700", "#1a0900", "#0a0400"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 131635,
    yearRange: "2012 - Atual",
    contentCount: 5,
    totalHours: 11,
    related: ["mazerunner", "divergente"],
  },
  {
    id: "mazerunner",
    name: "Maze Runner",
    shortName: "Maze Runner",
    tagline: "Lembre-se. Corra. Sobreviva.",
    description:
      "Thomas e os Corredores do Labirinto descobrem a verdade por trás do WICKED numa trilogia de ação e suspense.",
    color: "#556B2F",
    accentColor: "#6B8E23",
    bgGradient: ["#070a04", "#090c05", "#050803"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 295130,
    yearRange: "2014 - 2018",
    contentCount: 3,
    totalHours: 7,
    related: ["hungergames", "divergente"],
  },
  {
    id: "kingsman",
    name: "Kingsman",
    shortName: "Kingsman",
    tagline: "Manners maketh man",
    description:
      "A organização de espiões britânicos mais elegante do mundo. Ação estilosa e humor britânico afiado.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000520", "#000830", "#000318"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 391860,
    yearRange: "2014 - Atual",
    contentCount: 3,
    totalHours: 7,
    related: ["jamesbond", "missionimpossible"],
  },
  {
    id: "bourne",
    name: "Jason Bourne",
    shortName: "Bourne",
    tagline: "Quem sou eu? O que fiz?",
    description:
      "Jason Bourne, agente da CIA sem memória, descobre os segredos sombrios de seu passado enquanto foge.",
    color: "#6688AA",
    accentColor: "#88AACC",
    bgGradient: ["#060810", "#080a16", "#040610"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 31562,
    yearRange: "2002 - 2016",
    contentCount: 5,
    totalHours: 10,
    related: ["missionimpossible", "johnwick"],
  },
  {
    id: "rocky",
    name: "Rocky & Creed",
    shortName: "Rocky/Creed",
    tagline: "Yo, Adrian!",
    description:
      "De Rocky Balboa a Adonis Creed — a saga de superação mais emocionante do cinema de luta.",
    color: "#CC3300",
    accentColor: "#FF4422",
    bgGradient: ["#1a0500", "#1a0400", "#0a0200"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 1575,
    yearRange: "1976 - Atual",
    contentCount: 9,
    totalHours: 18,
    related: ["johnwick", "fastandfurious"],
  },
  {
    id: "diehard",
    name: "Duro de Matar",
    shortName: "Die Hard",
    tagline: "Yippee-ki-yay!",
    description:
      "John McClane, o policial certo no lugar errado. Cinco filmes de ação explosiva com Bruce Willis.",
    color: "#FF4500",
    accentColor: "#FF6633",
    bgGradient: ["#150300", "#1a0500", "#0a0200"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 1570,
    yearRange: "1988 - 2013",
    contentCount: 5,
    totalHours: 10,
    related: ["johnwick", "missionimpossible"],
  },
  {
    id: "madmax",
    name: "Mad Max",
    shortName: "Mad Max",
    tagline: "What a lovely day!",
    description:
      "Em um mundo pós-apocalíptico, Max Rockatansky sobrevive na wasteland. A saga mais intensa da estrada.",
    color: "#FF6600",
    accentColor: "#FF8822",
    bgGradient: ["#150800", "#1a0a00", "#0a0500"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 8945,
    yearRange: "1979 - Atual",
    contentCount: 5,
    totalHours: 10,
    related: ["johnwick", "fastandfurious"],
  },
  {
    id: "cobrakai",
    name: "Cobra Kai",
    shortName: "Cobra Kai",
    tagline: "Strike First. Strike Hard. No Mercy.",
    description:
      "30 anos depois de Karate Kid, Johnny Lawrence e Daniel LaRusso voltam a se enfrentar. A revanche mais épica da TV.",
    color: "#FFD700",
    accentColor: "#FFCC00",
    bgGradient: ["#150f00", "#1a1200", "#0a0a00"],
    category: "series",
    genre: "acao",
    fetchType: "tv",
    tmdbTvId: 77169,
    yearRange: "2018 - Atual",
    contentCount: 6,
    totalHours: 60,
    related: ["johnwick", "rocky"],
  },

  // ════════════════════════════════════════
  //  FICÇÃO CIENTÍFICA
  // ════════════════════════════════════════
  {
    id: "starwars",
    name: "Star Wars",
    shortName: "Star Wars",
    tagline: "Que a Força esteja com você",
    description:
      "Uma galáxia muito, muito distante. A saga Skywalker, spinoffs e séries Disney+ numa das maiores sagas do cinema.",
    color: "#FFE81F",
    accentColor: "#FFD700",
    bgGradient: ["#0a0805", "#080600", "#050400"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 10,
    relatedTvIds: [82856, 115036, 92830, 83867, 114461],
    yearRange: "1977 - Atual",
    contentCount: 18,
    totalHours: 45,
    bannerFeatured: true,
    isTop10: true,
    related: ["marvel", "alien"],
    chronologicalContent: [
      { tmdbId: 1893, type: "movie", label: "Ep. I — A Ameaça Fantasma", note: "32 ABY" },
      { tmdbId: 1894, type: "movie", label: "Ep. II — Ataque dos Clones", note: "22 ABY" },
      { tmdbId: 1895, type: "movie", label: "Ep. III — A Vingança dos Sith", note: "19 ABY" },
      { tmdbId: 348350, type: "movie", label: "Solo: Uma História Star Wars", note: "10 ABY" },
      { tmdbId: 92830, type: "tv", label: "Obi-Wan Kenobi (série)", note: "9 ABY" },
      { tmdbId: 83867, type: "tv", label: "Andor (série)", note: "5 ABY" },
      { tmdbId: 330459, type: "movie", label: "Rogue One", note: "0 ABY" },
      { tmdbId: 11, type: "movie", label: "Ep. IV — Uma Nova Esperança", note: "0 DBY" },
      { tmdbId: 1891, type: "movie", label: "Ep. V — O Império Contra-Ataca", note: "3 DBY" },
      { tmdbId: 1892, type: "movie", label: "Ep. VI — O Retorno de Jedi", note: "4 DBY" },
      { tmdbId: 82856, type: "tv", label: "The Mandalorian (série)", note: "9 DBY" },
      { tmdbId: 115036, type: "tv", label: "Livro de Boba Fett (série)", note: "9 DBY" },
      { tmdbId: 114461, type: "tv", label: "Ahsoka (série)", note: "9 DBY" },
      { tmdbId: 140607, type: "movie", label: "Ep. VII — O Despertar da Força", note: "34 DBY" },
      { tmdbId: 181808, type: "movie", label: "Ep. VIII — Os Últimos Jedi", note: "34 DBY" },
      { tmdbId: 181812, type: "movie", label: "Ep. IX — A Ascensão Skywalker", note: "35 DBY" },
    ],
  },
  {
    id: "startrek",
    name: "Star Trek",
    shortName: "Star Trek",
    tagline: "To boldly go where no one has gone before",
    description:
      "A maior saga de exploração espacial do cinema e TV. Da Enterprise clássica ao Picard moderno.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000515", "#000820", "#00030f"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 115575,
    relatedTvIds: [253, 1855, 67198, 85949],
    yearRange: "1979 - Atual",
    contentCount: 16,
    totalHours: 35,
    related: ["starwars", "alien"],
  },
  {
    id: "matrix",
    name: "Matrix",
    shortName: "Matrix",
    tagline: "A verdade está lá fora",
    description:
      "Neo descobre que a realidade é uma simulação e lidera a rebelião humana contra as máquinas.",
    color: "#00FF41",
    accentColor: "#33FF66",
    bgGradient: ["#001400", "#001800", "#000e00"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 2344,
    yearRange: "1999 - 2021",
    contentCount: 4,
    totalHours: 9,
    related: ["terminator", "alien"],
  },
  {
    id: "alien",
    name: "Alien",
    shortName: "Alien",
    tagline: "No espaço ninguém pode ouvir você gritar",
    description:
      "A criatura mais aterrorizante do cinema. A saga completa de Ripley contra os Xenomorfos.",
    color: "#AACC55",
    accentColor: "#BBDD66",
    bgGradient: ["#080e02", "#0a1204", "#060a02"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 8091,
    yearRange: "1979 - Atual",
    contentCount: 7,
    totalHours: 14,
    related: ["starwars", "terminator"],
  },
  {
    id: "terminator",
    name: "O Exterminador",
    shortName: "Terminator",
    tagline: "I'll be back",
    description:
      "Máquinas do futuro viajam no tempo para eliminar John Connor. A saga de resistência humana contra Skynet.",
    color: "#CC2200",
    accentColor: "#FF3311",
    bgGradient: ["#1a0600", "#1a0400", "#0a0200"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 528,
    yearRange: "1984 - Atual",
    contentCount: 6,
    totalHours: 12,
    related: ["alien", "matrix"],
  },
  {
    id: "jurassic",
    name: "Jurassic Park",
    shortName: "Jurassic",
    tagline: "A vida encontra um caminho",
    description:
      "Dinossauros ressurgem no mundo moderno. Da ilha original ao mundo dominado por dinos.",
    color: "#228B22",
    accentColor: "#32CD32",
    bgGradient: ["#051005", "#081408", "#040a04"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 328,
    yearRange: "1993 - 2022",
    contentCount: 6,
    totalHours: 13,
    related: ["alien", "terminator"],
  },
  {
    id: "strangerthings",
    name: "Stranger Things",
    shortName: "Stranger Things",
    tagline: "O Mundo Invertido te chama",
    description:
      "Hawkins, Indiana, esconde um mundo paralelo sombrio. Crianças e adolescentes enfrentam o misterioso Mundo Invertido.",
    color: "#CC0000",
    accentColor: "#FF2222",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "series",
    genre: "scifi",
    fetchType: "tv",
    tmdbTvId: 66732,
    yearRange: "2016 - Atual",
    contentCount: 4,
    totalHours: 38,
    bannerFeatured: true,
    isTop10: true,
    related: ["walkingdead", "theboys"],
  },
  {
    id: "transformers",
    name: "Transformers",
    shortName: "Transformers",
    tagline: "Mais que atende os olhos",
    description:
      "Autobots contra Decepticons. Robôs gigantes em batalhas épicas pelo destino da humanidade.",
    color: "#FF8C00",
    accentColor: "#FFA500",
    bgGradient: ["#150800", "#1a0a00", "#0a0500"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 8650,
    yearRange: "2007 - Atual",
    contentCount: 7,
    totalHours: 14,
    related: ["alien", "matrix"],
  },
  {
    id: "godzilla",
    name: "MonsterVerse",
    shortName: "Godzilla",
    tagline: "Long live the king",
    description:
      "Godzilla, King Kong e os Titãs. O universo compartilhado dos monstros mais épicos do cinema.",
    color: "#228B22",
    accentColor: "#32CD32",
    bgGradient: ["#031003", "#041204", "#020a02"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 535313,
    yearRange: "2014 - Atual",
    contentCount: 5,
    totalHours: 10,
    related: ["jurassic", "alien"],
  },
  {
    id: "predator",
    name: "Predador",
    shortName: "Predator",
    tagline: "If it bleeds, we can kill it",
    description:
      "O caçador intergaláctico mais letal enfrenta os maiores guerreiros da Terra. Pura adrenalina.",
    color: "#AA8800",
    accentColor: "#CCAA00",
    bgGradient: ["#100d00", "#150f00", "#0a0800"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 399,
    yearRange: "1987 - Atual",
    contentCount: 6,
    totalHours: 12,
    related: ["alien", "terminator"],
  },
  {
    id: "planetofapes",
    name: "Planeta dos Macacos",
    shortName: "Planeta dos Macacos",
    tagline: "Get your stinking paws off me",
    description:
      "A civilização dos símios domina a Terra. Da trilogia clássica à trilogia de César, uma das sagas mais aclamadas.",
    color: "#8B6914",
    accentColor: "#C49328",
    bgGradient: ["#0d0900", "#120c00", "#080600"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 173710,
    yearRange: "1968 - Atual",
    contentCount: 9,
    totalHours: 18,
    related: ["terminator", "matrix"],
  },
  {
    id: "blackmirror",
    name: "Black Mirror",
    shortName: "Black Mirror",
    tagline: "Tecnologia e suas consequências",
    description:
      "Antologia que explora o lado sombrio da tecnologia moderna. Cada episódio é uma distopia diferente.",
    color: "#333366",
    accentColor: "#6666CC",
    bgGradient: ["#050510", "#080815", "#03030a"],
    category: "series",
    genre: "scifi",
    fetchType: "tv",
    tmdbTvId: 42009,
    yearRange: "2011 - Atual",
    contentCount: 6,
    totalHours: 22,
    related: ["westworld", "strangerthings"],
  },
  {
    id: "westworld",
    name: "Westworld",
    shortName: "Westworld",
    tagline: "These violent delights have violent ends",
    description:
      "Um parque temático futurista onde robôs ganham consciência. Drama de ficção científica e suspense filosófico.",
    color: "#B8860B",
    accentColor: "#DAA520",
    bgGradient: ["#100d00", "#150f00", "#0a0800"],
    category: "series",
    genre: "scifi",
    fetchType: "tv",
    tmdbTvId: 63247,
    yearRange: "2016 - 2022",
    contentCount: 4,
    totalHours: 36,
    related: ["blackmirror", "strangerthings"],
  },
  {
    id: "thewitcher",
    name: "The Witcher",
    shortName: "The Witcher",
    tagline: "Evil is evil. Lesser, greater, middling",
    description:
      "Geralt de Rívia, o caçador de monstros, navega um mundo de conflitos e criaturas sobrenaturais.",
    color: "#CC9900",
    accentColor: "#FFCC00",
    bgGradient: ["#100c00", "#150f00", "#0a0800"],
    category: "series",
    genre: "scifi",
    fetchType: "tv",
    tmdbTvId: 71912,
    yearRange: "2019 - Atual",
    contentCount: 3,
    totalHours: 24,
    related: ["gameofthrones", "lotr"],
  },
  {
    id: "thelastofus",
    name: "The Last of Us",
    shortName: "The Last of Us",
    tagline: "When you're lost in the darkness, look for the light",
    description:
      "Joel e Ellie atravessam uma América pós-apocalíptica dominada por infectados. Uma das maiores séries da HBO.",
    color: "#556B2F",
    accentColor: "#78A035",
    bgGradient: ["#080a04", "#0a0c05", "#060803"],
    category: "series",
    genre: "scifi",
    fetchType: "tv",
    tmdbTvId: 100088,
    yearRange: "2023 - Atual",
    contentCount: 2,
    totalHours: 18,
    bannerFeatured: true,
    isTop10: true,
    related: ["walkingdead", "strangerthings"],
  },

  // ════════════════════════════════════════
  //  FANTASIA & MAGIA
  // ════════════════════════════════════════
  {
    id: "harrypotter",
    name: "Harry Potter",
    shortName: "Harry Potter",
    tagline: "A saga de Hogwarts",
    description:
      "A saga completa do bruxinho mais famoso do mundo, de Hogwarts ao confronto final com Voldemort.",
    color: "#B8860B",
    accentColor: "#DAA520",
    bgGradient: ["#0d0800", "#100c00", "#080600"],
    category: "filmes",
    genre: "fantasia",
    fetchType: "collection",
    tmdbCollectionId: 1241,
    yearRange: "2001 - 2011",
    contentCount: 8,
    totalHours: 19,
    bannerFeatured: true,
    isTop10: true,
    related: ["fantasticbeasts", "lotr"],
    chronologicalContent: [
      { tmdbId: 671, type: "movie", label: "A Pedra Filosofal", note: "Ano 1" },
      { tmdbId: 672, type: "movie", label: "A Câmara Secreta", note: "Ano 2" },
      { tmdbId: 673, type: "movie", label: "O Prisioneiro de Azkaban", note: "Ano 3" },
      { tmdbId: 674, type: "movie", label: "O Cálice de Fogo", note: "Ano 4" },
      { tmdbId: 675, type: "movie", label: "A Ordem da Fênix", note: "Ano 5" },
      { tmdbId: 767, type: "movie", label: "O Enigma do Príncipe", note: "Ano 6" },
      { tmdbId: 12444, type: "movie", label: "Relíquias da Morte — Parte 1", note: "Ano 7" },
      { tmdbId: 12445, type: "movie", label: "Relíquias da Morte — Parte 2", note: "Ano 7" },
    ],
  },
  {
    id: "fantasticbeasts",
    name: "Animais Fantásticos",
    shortName: "Animais Fantásticos",
    tagline: "O mundo mágico antes de Harry",
    description:
      "A saga de Newt Scamander que expande o universo do mundo mágico décadas antes de Harry Potter.",
    color: "#7B5EA7",
    accentColor: "#9B7EC8",
    bgGradient: ["#0d0520", "#0a0318", "#060210"],
    category: "filmes",
    genre: "fantasia",
    fetchType: "collection",
    tmdbCollectionId: 435259,
    yearRange: "2016 - 2022",
    contentCount: 3,
    totalHours: 7,
    related: ["harrypotter"],
  },
  {
    id: "lotr",
    name: "Senhor dos Anéis",
    shortName: "LOTR",
    tagline: "Uma jornada épica pela Terra-média",
    description:
      "A trilogia épica de J.R.R. Tolkien adaptada por Peter Jackson. Uma das maiores conquistas do cinema moderno.",
    color: "#8B7355",
    accentColor: "#C4A35A",
    bgGradient: ["#0a0800", "#100e00", "#080700"],
    category: "filmes",
    genre: "fantasia",
    fetchType: "collection",
    tmdbCollectionId: 119,
    yearRange: "2001 - 2003",
    contentCount: 3,
    totalHours: 11,
    bannerFeatured: true,
    isTop10: true,
    related: ["hobbit", "harrypotter"],
    chronologicalContent: [
      { tmdbId: 120, type: "movie", label: "A Sociedade do Anel", note: "Parte 1" },
      { tmdbId: 121, type: "movie", label: "As Duas Torres", note: "Parte 2" },
      { tmdbId: 122, type: "movie", label: "O Retorno do Rei", note: "Parte 3" },
    ],
  },
  {
    id: "hobbit",
    name: "O Hobbit",
    shortName: "Hobbit",
    tagline: "Uma jornada inesperada",
    description:
      "A aventura de Bilbo Bolseiro e os anões em busca de recuperar a Montanha Solitária do dragão Smaug.",
    color: "#6B8E23",
    accentColor: "#8FBC3C",
    bgGradient: ["#050a00", "#080e00", "#040700"],
    category: "filmes",
    genre: "fantasia",
    fetchType: "collection",
    tmdbCollectionId: 121938,
    yearRange: "2012 - 2014",
    contentCount: 3,
    totalHours: 9,
    related: ["lotr"],
  },
  {
    id: "gameofthrones",
    name: "Game of Thrones",
    shortName: "GoT",
    tagline: "Quando você joga o jogo dos tronos...",
    description:
      "A batalha pelo Trono de Ferro em Westeros. Intrigas, dragões e traições numa épica de fantasia medieval.",
    color: "#C0A060",
    accentColor: "#D4B870",
    bgGradient: ["#0d0a05", "#120e07", "#090705"],
    category: "series",
    genre: "fantasia",
    fetchType: "tv",
    tmdbTvId: 1399,
    relatedTvIds: [94997],
    yearRange: "2011 - 2019",
    contentCount: 8,
    totalHours: 70,
    bannerFeatured: true,
    isTop10: true,
    related: ["houseofdragon"],
  },
  {
    id: "houseofdragon",
    name: "House of the Dragon",
    shortName: "HotD",
    tagline: "A dança dos dragões",
    description:
      "A guerra civil da Casa Targaryen 200 anos antes de Game of Thrones.",
    color: "#C41E3A",
    accentColor: "#E83050",
    bgGradient: ["#1a0005", "#1a000a", "#0a0003"],
    category: "series",
    genre: "fantasia",
    fetchType: "tv",
    tmdbTvId: 94997,
    relatedTvIds: [1399],
    yearRange: "2022 - Atual",
    contentCount: 2,
    totalHours: 20,
    related: ["gameofthrones"],
  },
  {
    id: "vikings",
    name: "Vikings",
    shortName: "Vikings",
    tagline: "The Gods must be crazy",
    description:
      "Ragnar Lothbrok e seus descentes conquistam a Inglaterra e além. A saga nórdica mais épica da TV.",
    color: "#708090",
    accentColor: "#A0B0C0",
    bgGradient: ["#080a0d", "#0a0c10", "#060809"],
    category: "series",
    genre: "fantasia",
    fetchType: "tv",
    tmdbTvId: 44217,
    relatedTvIds: [96058],
    yearRange: "2013 - Atual",
    contentCount: 2,
    totalHours: 89,
    related: ["gameofthrones", "lotr"],
  },
  {
    id: "percyjackson",
    name: "Percy Jackson",
    shortName: "Percy Jackson",
    tagline: "Filho de Poseidon",
    description:
      "Percy Jackson descobre ser filho de um deus grego e enfrenta monstros e titãs para salvar o Olimpo.",
    color: "#4488CC",
    accentColor: "#66AAEE",
    bgGradient: ["#000d1a", "#001020", "#00080f"],
    category: "series",
    genre: "fantasia",
    fetchType: "tv",
    tmdbTvId: 229934,
    yearRange: "2023 - Atual",
    contentCount: 1,
    totalHours: 8,
    related: ["harrypotter", "lotr"],
  },
  {
    id: "narnia",
    name: "As Crônicas de Nárnia",
    shortName: "Nárnia",
    tagline: "Entre no guarda-roupa",
    description:
      "Quatro irmãos descobrem Nárnia, um mundo mágico governado pelo leão Aslan. Uma aventura épica para toda a família.",
    color: "#FFFFFF",
    accentColor: "#AADDFF",
    bgGradient: ["#050510", "#080818", "#03030c"],
    category: "filmes",
    genre: "fantasia",
    fetchType: "collection",
    tmdbCollectionId: 420,
    yearRange: "2005 - 2010",
    contentCount: 3,
    totalHours: 7,
    related: ["lotr", "harrypotter"],
  },

  // ════════════════════════════════════════
  //  TERROR & SUSPENSE
  // ════════════════════════════════════════
  {
    id: "walkingdead",
    name: "The Walking Dead",
    shortName: "TWD",
    tagline: "Sobreviva ou vire zumbi",
    description:
      "O apocalipse zumbi que redefiniu as séries de terror. A luta de sobreviventes num mundo sem lei.",
    color: "#556B2F",
    accentColor: "#6B8E23",
    bgGradient: ["#080a04", "#0a0c05", "#060804"],
    category: "series",
    genre: "terror",
    fetchType: "tv",
    tmdbTvId: 1402,
    relatedTvIds: [62286, 127534, 85385],
    yearRange: "2010 - 2022",
    contentCount: 5,
    totalHours: 175,
    bannerFeatured: true,
    related: ["theboys", "strangerthings"],
  },
  {
    id: "conjuring",
    name: "Universo Conjuring",
    shortName: "Conjuring",
    tagline: "Baseado em casos reais de horror",
    description:
      "Os detetives paranormais Ed e Lorraine Warren, Annabelle, a Freira e o Homem Torto. O universo de terror mais assustador.",
    color: "#8B0000",
    accentColor: "#CC1111",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "filmes",
    genre: "terror",
    fetchType: "keyword",
    tmdbKeywordId: 256599,
    yearRange: "2013 - Atual",
    contentCount: 8,
    totalHours: 16,
    related: ["walkingdead"],
  },
  {
    id: "it",
    name: "IT — A Coisa",
    shortName: "IT",
    tagline: "Eles flutuam lá embaixo",
    description:
      "Pennywise, o palhaço dançante, aterroriza Derry há séculos. A adaptação mais assustadora de Stephen King.",
    color: "#CC0000",
    accentColor: "#FF2222",
    bgGradient: ["#1a0000", "#140000", "#0a0000"],
    category: "filmes",
    genre: "terror",
    fetchType: "collection",
    tmdbCollectionId: 704773,
    yearRange: "2017 - 2019",
    contentCount: 2,
    totalHours: 5,
    related: ["conjuring", "walkingdead"],
  },
  {
    id: "halloween",
    name: "Halloween",
    shortName: "Halloween",
    tagline: "He's coming home",
    description:
      "Michael Myers, o assassino mascarado de Haddonfield. A franquia que definiu o slasher moderno.",
    color: "#FF6600",
    accentColor: "#FF8822",
    bgGradient: ["#150800", "#1a0a00", "#0a0500"],
    category: "filmes",
    genre: "terror",
    fetchType: "collection",
    tmdbCollectionId: 91361,
    yearRange: "1978 - Atual",
    contentCount: 13,
    totalHours: 22,
    related: ["conjuring", "it"],
  },
  {
    id: "scream",
    name: "Pânico",
    shortName: "Scream",
    tagline: "What's your favorite scary movie?",
    description:
      "O assassino Ghostface aterroriza Woodsboro. A franquia que reinventou o terror com meta-humor afiado.",
    color: "#FFFFFF",
    accentColor: "#FFFFFF",
    bgGradient: ["#050505", "#080808", "#030303"],
    category: "filmes",
    genre: "terror",
    fetchType: "collection",
    tmdbCollectionId: 2602,
    yearRange: "1996 - Atual",
    contentCount: 6,
    totalHours: 11,
    related: ["halloween", "conjuring"],
  },
  {
    id: "saw",
    name: "Jogos Mortais",
    shortName: "Saw",
    tagline: "I want to play a game",
    description:
      "Jigsaw e seus jogos sádicos. A franquia de terror mais lucrativa da história, com 10 filmes.",
    color: "#CC4400",
    accentColor: "#FF6622",
    bgGradient: ["#150400", "#1a0500", "#0a0200"],
    category: "filmes",
    genre: "terror",
    fetchType: "collection",
    tmdbCollectionId: 656,
    yearRange: "2004 - Atual",
    contentCount: 10,
    totalHours: 18,
    related: ["halloween", "conjuring"],
  },

  // ════════════════════════════════════════
  //  DRAMA & CRIME
  // ════════════════════════════════════════
  {
    id: "breakingbad",
    name: "Breaking Bad",
    shortName: "Breaking Bad",
    tagline: "I am the one who knocks",
    description:
      "Walter White transforma-se de professor de química em magnata do tráfico. A melhor série de drama já feita.",
    color: "#228B22",
    accentColor: "#32CD32",
    bgGradient: ["#041004", "#061406", "#030a03"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 1396,
    relatedTvIds: [60059],
    yearRange: "2008 - 2013",
    contentCount: 2,
    totalHours: 90,
    isTop10: true,
    related: ["narcos", "ozark"],
  },
  {
    id: "narcos",
    name: "Narcos",
    shortName: "Narcos",
    tagline: "Plata o plomo",
    description:
      "A ascensão e queda de Pablo Escobar e os cartéis colombianos. Baseado em história real.",
    color: "#CC6600",
    accentColor: "#FF8822",
    bgGradient: ["#150800", "#1a0b00", "#0a0500"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 63351,
    relatedTvIds: [72643],
    yearRange: "2015 - Atual",
    contentCount: 2,
    totalHours: 60,
    related: ["breakingbad", "ozark"],
  },
  {
    id: "sopranos",
    name: "The Sopranos",
    shortName: "Sopranos",
    tagline: "Family and business",
    description:
      "Tony Soprano, chefe da máfia de Nova Jersey, equilibra família e crime organizado. O maior drama da TV.",
    color: "#8B4513",
    accentColor: "#C4692A",
    bgGradient: ["#0d0600", "#120800", "#080400"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 1398,
    yearRange: "1999 - 2007",
    contentCount: 1,
    totalHours: 86,
    related: ["breakingbad", "peakyblinds"],
  },
  {
    id: "peakyblinds",
    name: "Peaky Blinders",
    shortName: "Peaky Blinders",
    tagline: "By order of the Peaky Blinders",
    description:
      "Tommy Shelby e a família Shelby dominam Birmingham pós-guerra. Crime, política e família num drama épico.",
    color: "#808080",
    accentColor: "#BBBBBB",
    bgGradient: ["#080808", "#0c0c0c", "#050505"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 60574,
    yearRange: "2013 - 2022",
    contentCount: 1,
    totalHours: 36,
    related: ["sopranos", "breakingbad"],
  },
  {
    id: "moneyheist",
    name: "La Casa de Papel",
    shortName: "La Casa de Papel",
    tagline: "Bella ciao",
    description:
      "O Professor planeja o maior roubo da história. Uma série espanhola que conquistou o mundo inteiro.",
    color: "#CC0000",
    accentColor: "#FF2222",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 71446,
    relatedTvIds: [176381],
    yearRange: "2017 - Atual",
    contentCount: 2,
    totalHours: 50,
    isTop10: true,
    related: ["breakingbad", "narcos"],
  },
  {
    id: "squidgame",
    name: "Round 6",
    shortName: "Round 6",
    tagline: "456 jogadores. Um prêmio. Sem piedade.",
    description:
      "Centenas de pessoas endividadas competem em jogos infantis com apostas mortais. O fenômeno global da Netflix.",
    color: "#FF4466",
    accentColor: "#FF6688",
    bgGradient: ["#150010", "#1a0015", "#0a0008"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 93405,
    yearRange: "2021 - Atual",
    contentCount: 2,
    totalHours: 14,
    isTop10: true,
    related: ["moneyheist", "breakingbad"],
  },
  {
    id: "ozark",
    name: "Ozark",
    shortName: "Ozark",
    tagline: "Family is the only currency",
    description:
      "Marty Byrde lava dinheiro para um cartel mexicano no interior do Missouri. Drama tenso e perturbador.",
    color: "#003366",
    accentColor: "#0055AA",
    bgGradient: ["#000510", "#000818", "#00030a"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 69737,
    yearRange: "2017 - 2022",
    contentCount: 1,
    totalHours: 44,
    related: ["breakingbad", "narcos"],
  },
  {
    id: "succession",
    name: "Succession",
    shortName: "Succession",
    tagline: "Who will succeed?",
    description:
      "A família Roy batalha pelo controle de um império midiático. Traição, poder e dinheiro em cada episódio.",
    color: "#CC9900",
    accentColor: "#EEBB00",
    bgGradient: ["#100d00", "#150f00", "#0a0800"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 76331,
    yearRange: "2018 - 2023",
    contentCount: 1,
    totalHours: 40,
    related: ["sopranos", "peakyblinds"],
  },
  {
    id: "yellowstone",
    name: "Yellowstone",
    shortName: "Yellowstone",
    tagline: "This land is not for sale",
    description:
      "A família Dutton defende sua propriedade no Montana contra incorporadoras e nações indígenas.",
    color: "#8B6914",
    accentColor: "#C49328",
    bgGradient: ["#0d0900", "#120c00", "#080600"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 73017,
    relatedTvIds: [162432, 220441],
    yearRange: "2018 - Atual",
    contentCount: 3,
    totalHours: 55,
    related: ["succession", "ozark"],
  },
  {
    id: "dark",
    name: "Dark",
    shortName: "Dark",
    tagline: "O começo é o fim e o fim é o começo",
    description:
      "Uma série alemã sobre viagem no tempo e quatro famílias interligadas ao longo de séculos. Obra-prima.",
    color: "#333366",
    accentColor: "#5555CC",
    bgGradient: ["#050510", "#080818", "#03030c"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 73541,
    yearRange: "2017 - 2020",
    contentCount: 1,
    totalHours: 26,
    related: ["blackmirror", "strangerthings"],
  },
  {
    id: "suits",
    name: "Suits",
    shortName: "Suits",
    tagline: "Dois advogados. Um segredo.",
    description:
      "Harvey Specter e Mike Ross dominam os tribunais de Nova York. O drama jurídico mais estiloso da TV.",
    color: "#003366",
    accentColor: "#0055AA",
    bgGradient: ["#000510", "#000818", "#00030a"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 37680,
    yearRange: "2011 - Atual",
    contentCount: 2,
    totalHours: 100,
    related: ["breakingbad", "succession"],
  },

  // ════════════════════════════════════════
  //  ANIMAÇÃO
  // ════════════════════════════════════════
  {
    id: "toystory",
    name: "Toy Story",
    shortName: "Toy Story",
    tagline: "Para o infinito e além!",
    description:
      "Woody, Buzz e os brinquedos de Andy numa saga emocionante de amizade, aventura e crescimento.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000820", "#000a28", "#000510"],
    category: "filmes",
    genre: "animacao",
    fetchType: "collection",
    tmdbCollectionId: 10194,
    yearRange: "1995 - 2019",
    contentCount: 4,
    totalHours: 6,
    related: ["shrek", "kungfupanda"],
  },
  {
    id: "shrek",
    name: "Shrek",
    shortName: "Shrek",
    tagline: "Estava tudo errado e deu tudo certo",
    description:
      "O ogro mais amado do cinema e seu fiel companheiro Burro em aventuras pelo reino de Far Far Away.",
    color: "#558B2F",
    accentColor: "#76C442",
    bgGradient: ["#061006", "#081408", "#040a04"],
    category: "filmes",
    genre: "animacao",
    fetchType: "collection",
    tmdbCollectionId: 230,
    yearRange: "2001 - Atual",
    contentCount: 5,
    totalHours: 8,
    related: ["toystory", "kungfupanda"],
  },
  {
    id: "kungfupanda",
    name: "Kung Fu Panda",
    shortName: "Kung Fu Panda",
    tagline: "Não existe segredo na sopa secreta",
    description:
      "Po, o panda desajeitado que se torna o Guerreiro Dragão e defende o Vale da Paz com kung fu incrível.",
    color: "#CC6600",
    accentColor: "#FF8822",
    bgGradient: ["#150800", "#1a0a00", "#0a0500"],
    category: "filmes",
    genre: "animacao",
    fetchType: "collection",
    tmdbCollectionId: 77816,
    yearRange: "2008 - Atual",
    contentCount: 4,
    totalHours: 7,
    related: ["shrek", "toystory"],
  },
  {
    id: "despicableme",
    name: "Meu Malvado Favorito",
    shortName: "Minions",
    tagline: "É muito difícil ser mau",
    description:
      "Gru, o vilão que se torna herói, e seus adoráveis Minions. A saga animada mais lucrativa da história.",
    color: "#FFD700",
    accentColor: "#FFEE44",
    bgGradient: ["#150f00", "#1a1200", "#0a0900"],
    category: "filmes",
    genre: "animacao",
    fetchType: "collection",
    tmdbCollectionId: 86066,
    yearRange: "2010 - Atual",
    contentCount: 6,
    totalHours: 10,
    isTop10: true,
    related: ["shrek", "toystory"],
  },
  {
    id: "iceage",
    name: "A Era do Gelo",
    shortName: "Ice Age",
    tagline: "Manny, Sid e Diego",
    description:
      "Manny o mamute, Sid o bicho-preguiça e Diego o tigre-dente-de-sabre em aventuras pela era glacial.",
    color: "#87CEEB",
    accentColor: "#B0E0FF",
    bgGradient: ["#050a12", "#080e18", "#03060d"],
    category: "filmes",
    genre: "animacao",
    fetchType: "collection",
    tmdbCollectionId: 8354,
    yearRange: "2002 - 2022",
    contentCount: 6,
    totalHours: 9,
    related: ["shrek", "kungfupanda"],
  },
  {
    id: "madagascar",
    name: "Madagascar",
    shortName: "Madagascar",
    tagline: "Move it, move it!",
    description:
      "Alex, Marty, Melman e Gloria escapam do zoológico e descobrem Madagascar. Pura diversão animada.",
    color: "#228B22",
    accentColor: "#32CD32",
    bgGradient: ["#041004", "#061406", "#030a03"],
    category: "filmes",
    genre: "animacao",
    fetchType: "collection",
    tmdbCollectionId: 14740,
    yearRange: "2005 - 2012",
    contentCount: 3,
    totalHours: 5,
    related: ["shrek", "iceage"],
  },
  {
    id: "howtotrainyourdragon",
    name: "Como Treinar Seu Dragão",
    shortName: "Dragão",
    tagline: "Seja o piloto do seu dragão",
    description:
      "Soluço e Banguela descobrem uma amizade impossível entre vikings e dragões. Uma trilogia emocionante.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000520", "#000830", "#000318"],
    category: "filmes",
    genre: "animacao",
    fetchType: "collection",
    tmdbCollectionId: 82967,
    yearRange: "2010 - Atual",
    contentCount: 4,
    totalHours: 7,
    related: ["toystory", "shrek"],
  },
  {
    id: "incredibles",
    name: "Os Incríveis",
    shortName: "Incríveis",
    tagline: "Onde todos são especiais, ninguém é",
    description:
      "A família super-heróis mais adorável do cinema. Bob Parr e sua família em aventuras de tirar o fôlego.",
    color: "#CC0000",
    accentColor: "#FF2222",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "filmes",
    genre: "animacao",
    fetchType: "collection",
    tmdbCollectionId: 468222,
    yearRange: "2004 - 2018",
    contentCount: 2,
    totalHours: 4,
    related: ["toystory", "shrek"],
  },
  {
    id: "simpsons",
    name: "Os Simpsons",
    shortName: "Simpsons",
    tagline: "D'oh!",
    description:
      "A família mais famosa da TV americana. Mais de 30 temporadas de comédia, sátira e cultura pop.",
    color: "#FFD700",
    accentColor: "#FFEE44",
    bgGradient: ["#150f00", "#1a1200", "#0a0900"],
    category: "series",
    genre: "animacao",
    fetchType: "tv",
    tmdbTvId: 456,
    yearRange: "1989 - Atual",
    contentCount: 1,
    totalHours: 700,
    related: ["familyguy", "futurama"],
  },
  {
    id: "familyguy",
    name: "Family Guy",
    shortName: "Family Guy",
    tagline: "Giggity Giggity!",
    description:
      "Peter Griffin e sua família disfuncional em Quahog. Humor irreverente, referências pop e piadas inesperadas.",
    color: "#0064FF",
    accentColor: "#4488FF",
    bgGradient: ["#000520", "#000a30", "#00031a"],
    category: "series",
    genre: "animacao",
    fetchType: "tv",
    tmdbTvId: 1434,
    yearRange: "1999 - Atual",
    contentCount: 1,
    totalHours: 400,
    related: ["simpsons", "southpark"],
  },
  {
    id: "southpark",
    name: "South Park",
    shortName: "South Park",
    tagline: "Oh my God, they killed Kenny!",
    description:
      "Stan, Kyle, Cartman e Kenny em Colorado. Sátira mordaz da cultura americana sem nenhum filtro.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000520", "#000830", "#000318"],
    category: "series",
    genre: "animacao",
    fetchType: "tv",
    tmdbTvId: 2190,
    yearRange: "1997 - Atual",
    contentCount: 1,
    totalHours: 350,
    related: ["familyguy", "simpsons"],
  },
  {
    id: "rickandmorty",
    name: "Rick and Morty",
    shortName: "Rick & Morty",
    tagline: "Wubba lubba dub dub!",
    description:
      "O cientista mais inteligente do universo e seu neto em aventuras interdimensionais. Ficção científica e comédia absurda.",
    color: "#33CC99",
    accentColor: "#55EEBB",
    bgGradient: ["#001510", "#001a14", "#000d09"],
    category: "series",
    genre: "animacao",
    fetchType: "tv",
    tmdbTvId: 60625,
    yearRange: "2013 - Atual",
    contentCount: 1,
    totalHours: 40,
    isTop10: true,
    related: ["futurama", "blackmirror"],
  },
  {
    id: "futurama",
    name: "Futurama",
    shortName: "Futurama",
    tagline: "Good news, everyone!",
    description:
      "Fry é congelado e acorda 1000 anos no futuro. Comédia de ficção científica com personagens inesquecíveis.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000520", "#000830", "#000318"],
    category: "series",
    genre: "animacao",
    fetchType: "tv",
    tmdbTvId: 615,
    yearRange: "1999 - Atual",
    contentCount: 1,
    totalHours: 90,
    related: ["simpsons", "rickandmorty"],
  },
  {
    id: "avatarairbender",
    name: "Avatar",
    shortName: "Avatar: A Lenda de Aang",
    tagline: "Water. Earth. Fire. Air.",
    description:
      "Aang, o último Mestre do Ar, deve dominar os quatro elementos para trazer paz ao mundo.",
    color: "#87CEEB",
    accentColor: "#ADD8FF",
    bgGradient: ["#050a12", "#080e18", "#03060d"],
    category: "series",
    genre: "animacao",
    fetchType: "tv",
    tmdbTvId: 246,
    relatedTvIds: [39006],
    yearRange: "2005 - 2014",
    contentCount: 2,
    totalHours: 45,
    related: ["rickandmorty", "simpsons"],
  },

  // ════════════════════════════════════════
  //  ANIMES
  // ════════════════════════════════════════
  {
    id: "dragonball",
    name: "Dragon Ball",
    shortName: "Dragon Ball",
    tagline: "O poder dos Super Saiyajins",
    description:
      "Goku e seus amigos em batalhas épicas pelo universo. Da infância ao guerreiro mais poderoso do multiverso.",
    color: "#FF8C00",
    accentColor: "#FFA500",
    bgGradient: ["#150800", "#180a00", "#0a0500"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 12609,
    relatedTvIds: [39230, 60554],
    yearRange: "1986 - Atual",
    contentCount: 8,
    totalHours: 600,
    bannerFeatured: true,
    isTop10: true,
    related: ["naruto", "onepiece"],
  },
  {
    id: "naruto",
    name: "Naruto",
    shortName: "Naruto",
    tagline: "Acredite no seu jeito ninja!",
    description:
      "A jornada de Naruto Uzumaki, do ninja rejeitado à Hokage da Vila da Folha.",
    color: "#FF8C00",
    accentColor: "#FF6600",
    bgGradient: ["#150600", "#1a0800", "#0a0400"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 46260,
    relatedTvIds: [31910, 70261],
    yearRange: "2002 - Atual",
    contentCount: 4,
    totalHours: 900,
    isTop10: true,
    related: ["dragonball", "onepiece", "bleach"],
  },
  {
    id: "onepiece",
    name: "One Piece",
    shortName: "One Piece",
    tagline: "Vou ser o Rei dos Piratas!",
    description:
      "Monkey D. Luffy navega pelo Grand Line em busca do lendário tesouro One Piece.",
    color: "#FF4500",
    accentColor: "#FF6347",
    bgGradient: ["#150300", "#1a0500", "#0a0200"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 37854,
    relatedTvIds: [228979],
    yearRange: "1999 - Atual",
    contentCount: 3,
    totalHours: 1100,
    isTop10: true,
    related: ["naruto", "dragonball"],
  },
  {
    id: "attackontitan",
    name: "Attack on Titan",
    shortName: "AoT",
    tagline: "A humanidade sob ataque",
    description:
      "Eren Yeager e o Batalhão de Reconhecimento lutam contra os Titãs. Uma das obras mais impactantes do anime moderno.",
    color: "#8B0000",
    accentColor: "#CC0000",
    bgGradient: ["#1a0000", "#140000", "#0a0000"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 1429,
    yearRange: "2013 - 2023",
    contentCount: 1,
    totalHours: 40,
    bannerFeatured: true,
    isTop10: true,
    related: ["naruto", "bleach"],
  },
  {
    id: "demonslayer",
    name: "Demon Slayer",
    shortName: "Demon Slayer",
    tagline: "Caçador de demônios",
    description:
      "Tanjiro Kamado busca vingança e a cura para sua irmã transformada em demônio. Animação deslumbrante.",
    color: "#CC2244",
    accentColor: "#FF3366",
    bgGradient: ["#1a0008", "#15000a", "#0a0005"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 85937,
    yearRange: "2019 - Atual",
    contentCount: 1,
    totalHours: 30,
    isTop10: true,
    related: ["naruto", "attackontitan"],
  },
  {
    id: "myheroacademia",
    name: "My Hero Academia",
    shortName: "Boku no Hero",
    tagline: "Plus Ultra!",
    description:
      "Izuku Midoriya nasce sem poderes num mundo de super-heróis, mas herda o maior poder de todos.",
    color: "#006400",
    accentColor: "#008B00",
    bgGradient: ["#001400", "#001800", "#000e00"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 65930,
    yearRange: "2016 - Atual",
    contentCount: 1,
    totalHours: 60,
    related: ["demonslayer", "naruto"],
  },
  {
    id: "jujutsukaisen",
    name: "Jujutsu Kaisen",
    shortName: "Jujutsu Kaisen",
    tagline: "Vou devorar tudo isso",
    description:
      "Yuji Itadori engole um dedo amaldiçoado e se torna hospedeiro de Ryomen Sukuna. Batalhas de exorcismo épicas.",
    color: "#6600CC",
    accentColor: "#8822FF",
    bgGradient: ["#080015", "#0a001a", "#05000d"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 95479,
    yearRange: "2020 - Atual",
    contentCount: 1,
    totalHours: 35,
    related: ["demonslayer", "myheroacademia"],
  },
  {
    id: "bleach",
    name: "Bleach",
    shortName: "Bleach",
    tagline: "Soul Reaper mais poderoso",
    description:
      "Ichigo Kurosaki, adolescente que se torna Soul Reaper e defende o mundo dos espíritos.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000515", "#000820", "#00030f"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 46261,
    yearRange: "2004 - Atual",
    contentCount: 1,
    totalHours: 380,
    related: ["naruto", "attackontitan"],
  },
  {
    id: "deathnote",
    name: "Death Note",
    shortName: "Death Note",
    tagline: "I'll take a potato chip... and eat it",
    description:
      "Light Yagami encontra um caderno que mata qualquer pessoa cujo nome for escrito nele. Suspense psicológico.",
    color: "#FFFFFF",
    accentColor: "#FFFFFF",
    bgGradient: ["#050505", "#080808", "#030303"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 13916,
    yearRange: "2006 - 2007",
    contentCount: 1,
    totalHours: 15,
    related: ["attackontitan", "naruto"],
  },
  {
    id: "fma",
    name: "Fullmetal Alchemist",
    shortName: "FMA",
    tagline: "Humankind cannot gain anything without first giving something",
    description:
      "Edward e Alphonse Elric buscam a Pedra Filosofal para recuperar seus corpos. Uma das melhores obras do anime.",
    color: "#FFD700",
    accentColor: "#FFCC00",
    bgGradient: ["#150f00", "#1a1200", "#0a0900"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 31911,
    yearRange: "2009 - 2010",
    contentCount: 1,
    totalHours: 25,
    related: ["deathnote", "attackontitan"],
  },
  {
    id: "pokemon",
    name: "Pokémon",
    shortName: "Pokémon",
    tagline: "Gotta catch 'em all!",
    description:
      "Ash Ketchum e Pikachu embarcam em uma jornada para se tornarem Mestres Pokémon.",
    color: "#FFD700",
    accentColor: "#FFCC00",
    bgGradient: ["#150f00", "#1a1200", "#0a0900"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 60572,
    relatedTvIds: [99966],
    yearRange: "1997 - Atual",
    contentCount: 2,
    totalHours: 1200,
    related: ["dragonball", "naruto"],
  },
  {
    id: "onepunchman",
    name: "One Punch Man",
    shortName: "One Punch Man",
    tagline: "Um soco para resolver tudo",
    description:
      "Saitama derrota qualquer inimigo com apenas um soco. A paródia mais épica e divertida do gênero shonen.",
    color: "#FFD700",
    accentColor: "#FFEE44",
    bgGradient: ["#150f00", "#1a1200", "#0a0900"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 63926,
    yearRange: "2015 - Atual",
    contentCount: 1,
    totalHours: 24,
    related: ["myheroacademia", "demonslayer"],
  },
  {
    id: "chainsawman",
    name: "Chainsaw Man",
    shortName: "Chainsaw Man",
    tagline: "Fazer contratos com demônios",
    description:
      "Denji se funde com um demônio-motosserra e trabalha para uma agência de caça a demônios. Gore e emoção.",
    color: "#CC0000",
    accentColor: "#FF2222",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 120089,
    yearRange: "2022 - Atual",
    contentCount: 1,
    totalHours: 12,
    related: ["demonslayer", "jujutsukaisen"],
  },
  {
    id: "spyxfamily",
    name: "Spy x Family",
    shortName: "Spy x Family",
    tagline: "A família perfeita é uma missão",
    description:
      "Um espião, uma assassina e uma criança telepata formam a família mais estranha e adorável do anime.",
    color: "#FFFFFF",
    accentColor: "#FFFFFF",
    bgGradient: ["#050505", "#080808", "#030303"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 121532,
    yearRange: "2022 - Atual",
    contentCount: 1,
    totalHours: 20,
    related: ["myheroacademia", "demonslayer"],
  },
  {
    id: "hunterxhunter",
    name: "Hunter x Hunter",
    shortName: "HxH",
    tagline: "Gon Freecss está determinado",
    description:
      "Gon Freecss parte para se tornar um Hunter e encontrar seu pai. Uma das histórias mais profundas do anime.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000520", "#000830", "#000318"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 46298,
    yearRange: "2011 - 2014",
    contentCount: 1,
    totalHours: 60,
    related: ["naruto", "demonslayer"],
  },

  // ════════════════════════════════════════
  //  SUPER-HERÓIS — mais
  // ════════════════════════════════════════
  {
    id: "venom",
    name: "Venom",
    shortName: "Venom",
    tagline: "We are Venom",
    description:
      "Eddie Brock se une ao simbionte alienígena Venom. Anti-herói brutal no universo do Homem-Aranha.",
    color: "#1A1A2E",
    accentColor: "#888888",
    bgGradient: ["#050508", "#080810", "#030305"],
    category: "filmes",
    genre: "superherois",
    fetchType: "collection",
    tmdbCollectionId: 555709,
    yearRange: "2018 - Atual",
    contentCount: 3,
    totalHours: 6,
    related: ["spiderman", "marvel"],
  },
  {
    id: "thor",
    name: "Thor",
    shortName: "Thor",
    tagline: "Deus do Trovão",
    description:
      "Thor Odinson, o deus nórdico do trovão e herói da Marvel. Asgard, Mjolnir e os Vingadores.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000520", "#000830", "#000318"],
    category: "filmes",
    genre: "superherois",
    fetchType: "collection",
    tmdbCollectionId: 131296,
    yearRange: "2011 - Atual",
    contentCount: 4,
    totalHours: 9,
    related: ["marvel", "dc"],
  },
  {
    id: "wonderwoman",
    name: "Mulher-Maravilha",
    shortName: "Wonder Woman",
    tagline: "A guerreira mais poderosa do DC",
    description:
      "Diana, princesa amazona, protege a humanidade como a Mulher-Maravilha. Uma das super-heroínas mais icônicas.",
    color: "#CC0000",
    accentColor: "#FFD700",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "filmes",
    genre: "superherois",
    fetchType: "collection",
    tmdbCollectionId: 468552,
    yearRange: "2017 - Atual",
    contentCount: 2,
    totalHours: 5,
    related: ["dc", "marvel"],
  },

  // ════════════════════════════════════════
  //  AÇÃO — mais
  // ════════════════════════════════════════
  {
    id: "dune",
    name: "Duna",
    shortName: "Duna",
    tagline: "O deserto é o poder",
    description:
      "Paul Atreides lidera os Fremen de Arrakis. A saga de ficção científica épica de Frank Herbert.",
    color: "#C8A96E",
    accentColor: "#E8C97E",
    bgGradient: ["#100c04", "#150f06", "#0a0803"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 726871,
    yearRange: "2021 - Atual",
    contentCount: 2,
    totalHours: 5,
    related: ["starwars", "matrix"],
  },
  {
    id: "oceans",
    name: "Ocean's",
    shortName: "Ocean's",
    tagline: "O maior roubo da história",
    description:
      "Danny Ocean e sua equipe de especialistas planejam os roubos mais elaborados do cinema. Estilo e charme.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000520", "#000830", "#000318"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 304,
    yearRange: "2001 - 2018",
    contentCount: 4,
    totalHours: 8,
    related: ["johnwick", "missionimpossible"],
  },
  {
    id: "taken",
    name: "Busca Implacável",
    shortName: "Taken",
    tagline: "I will find you and I will kill you",
    description:
      "Bryan Mills usa habilidades específicas para resgatar sua família de sequestradores. Ação sem parar.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000520", "#000830", "#000318"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 162569,
    yearRange: "2008 - 2014",
    contentCount: 3,
    totalHours: 6,
    related: ["johnwick", "bourne"],
  },
  {
    id: "expendables",
    name: "Os Mercenários",
    shortName: "Expendables",
    tagline: "Todos os ícones de ação juntos",
    description:
      "Stallone, Schwarzenegger, Statham, Li e muitos outros numa missão impossível. O maior elenco de ação da história.",
    color: "#CC4400",
    accentColor: "#FF6622",
    bgGradient: ["#150400", "#1a0500", "#0a0200"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 126125,
    yearRange: "2010 - Atual",
    contentCount: 4,
    totalHours: 8,
    related: ["johnwick", "fastandfurious"],
  },
  {
    id: "jackreacher",
    name: "Jack Reacher",
    shortName: "Jack Reacher",
    tagline: "Chegou. Viu. Venceu.",
    description:
      "Jack Reacher, ex-policial militar, investiga crimes usando apenas suas habilidades e instintos.",
    color: "#CC9900",
    accentColor: "#FFCC00",
    bgGradient: ["#100c00", "#150f00", "#0a0800"],
    category: "series",
    genre: "acao",
    fetchType: "tv",
    tmdbTvId: 108978,
    yearRange: "2022 - Atual",
    contentCount: 1,
    totalHours: 16,
    related: ["johnwick", "bourne"],
  },

  // ════════════════════════════════════════
  //  FICÇÃO CIENTÍFICA — mais
  // ════════════════════════════════════════
  {
    id: "backtothefuture",
    name: "De Volta para o Futuro",
    shortName: "BTTF",
    tagline: "Roads? Where we're going, we don't need roads",
    description:
      "Marty McFly e Doc Brown viajam no tempo num DeLorean. A trilogia de ficção científica mais amada de todos os tempos.",
    color: "#FFD700",
    accentColor: "#FFEE44",
    bgGradient: ["#150f00", "#1a1200", "#0a0900"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 264,
    yearRange: "1985 - 1990",
    contentCount: 3,
    totalHours: 6,
    related: ["matrix", "terminator"],
  },
  {
    id: "interstellar",
    name: "Christopher Nolan",
    shortName: "Nolan",
    tagline: "Filmes que desafiam o espaço e o tempo",
    description:
      "A obra de Christopher Nolan: Interstellar, Inception, Tenet e Oppenheimer. Cinema que desafia a mente.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000520", "#000830", "#000318"],
    category: "filmes",
    genre: "scifi",
    fetchType: "search",
    searchQuery: "Interstellar Inception Tenet",
    searchType: "movie",
    yearRange: "2000 - Atual",
    contentCount: 8,
    totalHours: 20,
    related: ["matrix", "blackmirror"],
  },
  {
    id: "lostinspace",
    name: "Perdidos no Espaço",
    shortName: "Lost in Space",
    tagline: "Danger, Will Robinson!",
    description:
      "A família Robinson sobrevive após uma catástrofe e explora planetas alienígenas para encontrar o caminho de volta.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000520", "#000830", "#000318"],
    category: "series",
    genre: "scifi",
    fetchType: "tv",
    tmdbTvId: 75758,
    yearRange: "2018 - 2021",
    contentCount: 1,
    totalHours: 30,
    related: ["starwars", "startrek"],
  },
  {
    id: "theexpanse",
    name: "The Expanse",
    shortName: "The Expanse",
    tagline: "A humanidade conquistou o sistema solar",
    description:
      "Séculos no futuro, humanos colonizaram Marte e o cinturão de asteroides. Uma das ficções científicas mais realistas da TV.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000520", "#000830", "#000318"],
    category: "series",
    genre: "scifi",
    fetchType: "tv",
    tmdbTvId: 63639,
    yearRange: "2015 - 2022",
    contentCount: 1,
    totalHours: 54,
    related: ["startrek", "starwars"],
  },
  {
    id: "foundation",
    name: "Fundação",
    shortName: "Foundation",
    tagline: "O fim do Império Galáctico",
    description:
      "Hari Seldon prevê a queda do Império Galáctico. Uma das maiores sagas da ficção científica adaptada para a Apple TV+.",
    color: "#FF8C00",
    accentColor: "#FFA500",
    bgGradient: ["#150800", "#1a0a00", "#0a0500"],
    category: "series",
    genre: "scifi",
    fetchType: "tv",
    tmdbTvId: 93974,
    yearRange: "2021 - Atual",
    contentCount: 1,
    totalHours: 20,
    related: ["starwars", "theexpanse"],
  },

  // ════════════════════════════════════════
  //  FANTASIA — mais
  // ════════════════════════════════════════
  {
    id: "ringsofpower",
    name: "Anéis de Poder",
    shortName: "Rings of Power",
    tagline: "A Segunda Era da Terra-média",
    description:
      "A história de Sauron e os Anéis de Poder milhares de anos antes de O Senhor dos Anéis.",
    color: "#8B7355",
    accentColor: "#C4A35A",
    bgGradient: ["#0a0800", "#100e00", "#080700"],
    category: "series",
    genre: "fantasia",
    fetchType: "tv",
    tmdbTvId: 84773,
    yearRange: "2022 - Atual",
    contentCount: 1,
    totalHours: 16,
    related: ["lotr", "hobbit"],
  },
  {
    id: "wheeloftime",
    name: "A Roda do Tempo",
    shortName: "Wheel of Time",
    tagline: "O Dragão vai renascer",
    description:
      "Moiraine busca o Dragon Reborn numa Terra fantástica onde a magia existe. Baseada na épica série de Robert Jordan.",
    color: "#8B0000",
    accentColor: "#CC0000",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "series",
    genre: "fantasia",
    fetchType: "tv",
    tmdbTvId: 71914,
    yearRange: "2021 - Atual",
    contentCount: 1,
    totalHours: 16,
    related: ["gameofthrones", "lotr"],
  },
  {
    id: "malazan",
    name: "Wednesday",
    shortName: "Wednesday",
    tagline: "I don't want to be normal. Never have, never will.",
    description:
      "Wednesday Addams frequenta a Academia Nevermore, uma escola para excepcionais, enquanto resolve mistérios sombrios.",
    color: "#1A1A2E",
    accentColor: "#AAAAAA",
    bgGradient: ["#050508", "#080810", "#030305"],
    category: "series",
    genre: "fantasia",
    fetchType: "tv",
    tmdbTvId: 119051,
    yearRange: "2022 - Atual",
    contentCount: 1,
    totalHours: 8,
    isTop10: true,
    related: ["strangerthings", "harrypotter"],
  },

  // ════════════════════════════════════════
  //  TERROR — mais
  // ════════════════════════════════════════
  {
    id: "quietplace",
    name: "Um Lugar Silencioso",
    shortName: "Quiet Place",
    tagline: "Se eles ouvirem, você está morto",
    description:
      "Uma família sobrevive em silêncio absoluto para evitar criaturas que caçam pelo som. Terror intenso e silencioso.",
    color: "#556B2F",
    accentColor: "#6B8E23",
    bgGradient: ["#080a04", "#0a0c05", "#060803"],
    category: "filmes",
    genre: "terror",
    fetchType: "collection",
    tmdbCollectionId: 521294,
    yearRange: "2018 - Atual",
    contentCount: 3,
    totalHours: 6,
    related: ["conjuring", "walkingdead"],
  },
  {
    id: "evildead",
    name: "Evil Dead",
    shortName: "Evil Dead",
    tagline: "Groovy",
    description:
      "O Livro dos Mortos desperta demônios na cabana dos horrores. A franquia de terror mais cult do cinema.",
    color: "#8B0000",
    accentColor: "#CC1111",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "filmes",
    genre: "terror",
    fetchType: "collection",
    tmdbCollectionId: 107,
    yearRange: "1981 - Atual",
    contentCount: 5,
    totalHours: 9,
    related: ["halloween", "conjuring"],
  },
  {
    id: "residentevil",
    name: "Resident Evil",
    shortName: "Resident Evil",
    tagline: "Welcome to Raccoon City",
    description:
      "Alice e os sobreviventes enfrentam zumbis e o vírus-T da Umbrella Corporation. Ação e terror ao extremo.",
    color: "#CC0000",
    accentColor: "#FF2222",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "filmes",
    genre: "terror",
    fetchType: "collection",
    tmdbCollectionId: 17255,
    yearRange: "2002 - Atual",
    contentCount: 7,
    totalHours: 14,
    related: ["walkingdead", "conjuring"],
  },
  {
    id: "thepurge",
    name: "A Purga",
    shortName: "The Purge",
    tagline: "Uma noite. Sem regras.",
    description:
      "Uma vez por ano, todos os crimes são legais por 12 horas. A franquia de terror político mais perturbadora.",
    color: "#CC0000",
    accentColor: "#FF2222",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "filmes",
    genre: "terror",
    fetchType: "collection",
    tmdbCollectionId: 255987,
    yearRange: "2013 - Atual",
    contentCount: 5,
    totalHours: 9,
    related: ["conjuring", "halloween"],
  },

  // ════════════════════════════════════════
  //  DRAMA — mais
  // ════════════════════════════════════════
  {
    id: "friends",
    name: "Friends",
    shortName: "Friends",
    tagline: "I'll be there for you",
    description:
      "Seis amigos vivem em Nova York e passam pelas alegrias e desafios da vida adulta. A série mais amada da TV.",
    color: "#FFCC00",
    accentColor: "#FFEE44",
    bgGradient: ["#150f00", "#1a1200", "#0a0900"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 1668,
    yearRange: "1994 - 2004",
    contentCount: 1,
    totalHours: 85,
    isTop10: true,
    related: ["theoffice", "seinfeld"],
  },
  {
    id: "theoffice",
    name: "The Office",
    shortName: "The Office",
    tagline: "Dunder Mifflin Paper Company",
    description:
      "O dia a dia de uma empresa de papel em Scranton, Pennsylvania. Mockumentary que redefiniu a comédia na TV.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000520", "#000830", "#000318"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 2316,
    yearRange: "2005 - 2013",
    contentCount: 1,
    totalHours: 73,
    related: ["friends", "parksandrec"],
  },
  {
    id: "parksandrec",
    name: "Parks and Recreation",
    shortName: "Parks & Rec",
    tagline: "Pawnee: City of Unity. City of Pride. City of Power.",
    description:
      "Leslie Knope e a equipe do departamento de parques de Pawnee. Comédia otimista e emocionante.",
    color: "#CC8800",
    accentColor: "#FFAA00",
    bgGradient: ["#150a00", "#1a0c00", "#0a0600"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 8592,
    yearRange: "2009 - 2015",
    contentCount: 1,
    totalHours: 72,
    related: ["theoffice", "friends"],
  },
  {
    id: "truedetective",
    name: "True Detective",
    shortName: "True Detective",
    tagline: "Time is a flat circle",
    description:
      "Detetives investigam crimes brutais e perturbadores em diferentes épocas e locais. Antologia de suspense noir.",
    color: "#556B2F",
    accentColor: "#6B8E23",
    bgGradient: ["#080a04", "#0a0c05", "#060803"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 46648,
    yearRange: "2014 - Atual",
    contentCount: 1,
    totalHours: 30,
    related: ["mindhunter", "fargo"],
  },
  {
    id: "mindhunter",
    name: "Mindhunter",
    shortName: "Mindhunter",
    tagline: "Como se pega um assassino que não existe?",
    description:
      "Agentes do FBI desenvolvem técnicas de perfil criminal entrevistando os serial killers mais notórios dos EUA.",
    color: "#333366",
    accentColor: "#5555CC",
    bgGradient: ["#050510", "#080818", "#03030c"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 67744,
    yearRange: "2017 - 2019",
    contentCount: 1,
    totalHours: 19,
    related: ["truedetective", "breakingbad"],
  },
  {
    id: "fargo",
    name: "Fargo",
    shortName: "Fargo",
    tagline: "This is a true story",
    description:
      "Crimes bizarros e personagens memoráveis no gélido Midwest americano. Antologia noir inspirada no filme dos Coen.",
    color: "#87CEEB",
    accentColor: "#ADD8FF",
    bgGradient: ["#050a12", "#080e18", "#03060d"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 60622,
    yearRange: "2014 - Atual",
    contentCount: 1,
    totalHours: 40,
    related: ["truedetective", "ozark"],
  },
  {
    id: "sherlock",
    name: "Sherlock",
    shortName: "Sherlock",
    tagline: "Elementary, my dear Watson",
    description:
      "Sherlock Holmes e Watson resolvem os crimes mais complexos de Londres no século XXI. BBC na melhor forma.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000520", "#000830", "#000318"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 19885,
    yearRange: "2010 - 2017",
    contentCount: 1,
    totalHours: 13,
    related: ["truedetective", "mindhunter"],
  },
  {
    id: "thecrown",
    name: "The Crown",
    shortName: "The Crown",
    tagline: "A história da família real britânica",
    description:
      "A história da Rainha Elizabeth II e a família real britânica. Drama épico de produção impecável da Netflix.",
    color: "#C0A000",
    accentColor: "#E8C000",
    bgGradient: ["#100d00", "#150f00", "#080700"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 65494,
    yearRange: "2016 - 2023",
    contentCount: 1,
    totalHours: 50,
    related: ["succession", "peakyblinds"],
  },
  {
    id: "euphoria",
    name: "Euphoria",
    shortName: "Euphoria",
    tagline: "The kids are not alright",
    description:
      "Rue e seus amigos navegam drogas, identidade e relacionamentos no ensino médio. Drama visceral da HBO.",
    color: "#6600CC",
    accentColor: "#8822FF",
    bgGradient: ["#080015", "#0a001a", "#05000d"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 85552,
    yearRange: "2019 - Atual",
    contentCount: 1,
    totalHours: 18,
    related: ["thecrown", "succession"],
  },
  {
    id: "lucifer",
    name: "Lúcifer",
    shortName: "Lucifer",
    tagline: "O Diabo está no detalhe",
    description:
      "Lucifer Morningstar abandona o inferno e abre um clube em Los Angeles, ajudando a LAPD a resolver crimes.",
    color: "#CC0000",
    accentColor: "#FF2222",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 63174,
    yearRange: "2016 - 2021",
    contentCount: 1,
    totalHours: 66,
    related: ["thewitcher", "sherlock"],
  },
  {
    id: "dexter",
    name: "Dexter",
    shortName: "Dexter",
    tagline: "Tonight's the night",
    description:
      "Dexter Morgan é analista forense de dia e serial killer justiceiro de noite. Um dos anti-heróis mais fascinantes da TV.",
    color: "#8B0000",
    accentColor: "#CC1111",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 1405,
    relatedTvIds: [126925],
    yearRange: "2006 - Atual",
    contentCount: 2,
    totalHours: 100,
    related: ["breakingbad", "truedetective"],
  },
  {
    id: "prison",
    name: "Prison Break",
    shortName: "Prison Break",
    tagline: "Eles têm um plano",
    description:
      "Michael Scofield se deixa prender para libertar seu irmão falsamente condenado à morte. Suspense inesquecível.",
    color: "#CC4400",
    accentColor: "#FF6622",
    bgGradient: ["#150400", "#1a0500", "#0a0200"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 2288,
    yearRange: "2005 - 2017",
    contentCount: 1,
    totalHours: 90,
    related: ["suits", "breakingbad"],
  },
  {
    id: "houseofcards",
    name: "House of Cards",
    shortName: "House of Cards",
    tagline: "Poder. Ambição. Traição.",
    description:
      "Frank Underwood manipula o sistema político americano para chegar à presidência. Drama político impecável.",
    color: "#CC0000",
    accentColor: "#FF2222",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 1425,
    yearRange: "2013 - 2018",
    contentCount: 1,
    totalHours: 65,
    related: ["succession", "ozark"],
  },
  {
    id: "power",
    name: "Power",
    shortName: "Power",
    tagline: "Ghost não vai embora fácil",
    description:
      "James St. Patrick, o Ghost, vive entre o mundo das drogas e a vida legítima em Nova York. Crime e ambição.",
    color: "#8B0000",
    accentColor: "#CC1111",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "series",
    genre: "drama",
    fetchType: "tv",
    tmdbTvId: 54650,
    relatedTvIds: [87914, 119451],
    yearRange: "2014 - Atual",
    contentCount: 3,
    totalHours: 70,
    related: ["narcos", "breakingbad"],
  },

  // ════════════════════════════════════════
  //  ANIMAÇÃO — mais
  // ════════════════════════════════════════
  {
    id: "frozen",
    name: "Frozen",
    shortName: "Frozen",
    tagline: "Let it go",
    description:
      "Elsa libera seus poderes de gelo e Moana busca salvar o reino. A saga de princesas Disney mais amada da modernidade.",
    color: "#87CEEB",
    accentColor: "#ADD8FF",
    bgGradient: ["#050a12", "#080e18", "#03060d"],
    category: "filmes",
    genre: "animacao",
    fetchType: "collection",
    tmdbCollectionId: 386382,
    yearRange: "2013 - Atual",
    contentCount: 3,
    totalHours: 5,
    related: ["toystory", "shrek"],
  },
  {
    id: "spiderverse",
    name: "Aranhaverso",
    shortName: "Spider-Verse",
    tagline: "Qualquer um pode usar a máscara",
    description:
      "Miles Morales e a teia de Aranhas de multiversos diferentes. Animação revolucionária premiada com o Oscar.",
    color: "#E01020",
    accentColor: "#FF2233",
    bgGradient: ["#1a0002", "#150003", "#0a0001"],
    category: "filmes",
    genre: "animacao",
    fetchType: "collection",
    tmdbCollectionId: 573436,
    yearRange: "2018 - Atual",
    contentCount: 3,
    totalHours: 5,
    related: ["spiderman", "marvel"],
  },
  {
    id: "cars",
    name: "Carros",
    shortName: "Cars",
    tagline: "Ka-chow!",
    description:
      "Relâmpago McQueen descobre que há mais na vida do que vencer corridas. A Pixar mais divertida para toda a família.",
    color: "#CC3300",
    accentColor: "#FF4422",
    bgGradient: ["#1a0500", "#1a0400", "#0a0200"],
    category: "filmes",
    genre: "animacao",
    fetchType: "collection",
    tmdbCollectionId: 87118,
    yearRange: "2006 - 2017",
    contentCount: 3,
    totalHours: 5,
    related: ["toystory", "kungfupanda"],
  },
  {
    id: "howl",
    name: "Studio Ghibli",
    shortName: "Ghibli",
    tagline: "Miyazaki e a magia da animação japonesa",
    description:
      "Spirited Away, Meu Vizinho Totoro, Princesa Mononoke. O estúdio de animação mais respeitado do mundo.",
    color: "#228B22",
    accentColor: "#32CD32",
    bgGradient: ["#041004", "#061406", "#030a03"],
    category: "filmes",
    genre: "animacao",
    fetchType: "keyword",
    tmdbKeywordId: 5765,
    yearRange: "1984 - Atual",
    contentCount: 24,
    totalHours: 45,
    related: ["toystory", "shrek"],
  },

  // ════════════════════════════════════════
  //  ANIME — mais
  // ════════════════════════════════════════
  {
    id: "swordartonline",
    name: "Sword Art Online",
    shortName: "SAO",
    tagline: "Jogadores presos num jogo virtual",
    description:
      "Kirito fica preso num MMORPG onde morrer no jogo significa morrer na vida real. Isekai pioneiro.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000520", "#000830", "#000318"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 45782,
    yearRange: "2012 - Atual",
    contentCount: 1,
    totalHours: 60,
    related: ["naruto", "demonslayer"],
  },
  {
    id: "vinlandsaga",
    name: "Vinland Saga",
    shortName: "Vinland Saga",
    tagline: "Uma saga de guerra e redenção",
    description:
      "Thorfinn busca vingança pelo pai assassinado em plena Era dos Vikings. Um dos melhores animes recentes.",
    color: "#8B6914",
    accentColor: "#C49328",
    bgGradient: ["#0d0900", "#120c00", "#080600"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 94893,
    yearRange: "2019 - Atual",
    contentCount: 1,
    totalHours: 50,
    related: ["attackontitan", "bleach"],
  },
  {
    id: "mobpsycho",
    name: "Mob Psycho 100",
    shortName: "Mob Psycho",
    tagline: "100% emoção",
    description:
      "Shigeo Kageyama, o Mob, é um adolescente com poderes psíquicos absurdos que tenta viver normalmente.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000520", "#000830", "#000318"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 72182,
    yearRange: "2016 - Atual",
    contentCount: 1,
    totalHours: 25,
    related: ["onepunchman", "myheroacademia"],
  },
  {
    id: "evangelion",
    name: "Neon Genesis Evangelion",
    shortName: "Evangelion",
    tagline: "Os Anjos estão chegando",
    description:
      "Shinji pilota o robô Evangelion para salvar a humanidade dos Anjos. Obra-prima psicológica do anime.",
    color: "#CC0000",
    accentColor: "#FF2222",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 890,
    yearRange: "1995 - Atual",
    contentCount: 1,
    totalHours: 15,
    related: ["attackontitan", "deathnote"],
  },
  {
    id: "cowboybebop",
    name: "Cowboy Bebop",
    shortName: "Cowboy Bebop",
    tagline: "3, 2, 1 — let's jam!",
    description:
      "Caçadores de recompensas no espaço em 2071. Jazz, ação e existencialismo numa das obras mais icônicas do anime.",
    color: "#FFD700",
    accentColor: "#FFCC00",
    bgGradient: ["#150f00", "#1a1200", "#0a0900"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 2552,
    yearRange: "1998 - 1999",
    contentCount: 1,
    totalHours: 11,
    related: ["evangelion", "deathnote"],
  },
  {
    id: "blackclover",
    name: "Black Clover",
    shortName: "Black Clover",
    tagline: "Vou me tornar o Rei Mago!",
    description:
      "Asta nasce sem magia num mundo de magos. Com esforço e sua espada anti-mágica, ele aspira ao maior título.",
    color: "#228B22",
    accentColor: "#32CD32",
    bgGradient: ["#041004", "#061406", "#030a03"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 71930,
    yearRange: "2017 - Atual",
    contentCount: 1,
    totalHours: 100,
    related: ["naruto", "myheroacademia"],
  },
  {
    id: "tokyoghoul",
    name: "Tokyo Ghoul",
    shortName: "Tokyo Ghoul",
    tagline: "Entre ghouls e humanos",
    description:
      "Kaneki Ken se transforma num meio-ghoul e navega entre dois mundos. Dark fantasy urbano perturbador.",
    color: "#8B0000",
    accentColor: "#CC1111",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 61374,
    yearRange: "2014 - 2018",
    contentCount: 1,
    totalHours: 24,
    related: ["demonslayer", "attackontitan"],
  },
];

// ── Helpers ───────────────────────────────────────────────────
export const BANNER_FRANCHISES = FRANCHISES.filter((f) => f.bannerFeatured);
export const TOP10_FRANCHISES = FRANCHISES.filter((f) => f.isTop10);
export const FEATURED_FRANCHISE = FRANCHISES.find((f) => f.id === "marvel")!;
export const getFranchise = (id: string) => FRANCHISES.find((f) => f.id === id);

export const GENRE_SECTIONS: { genre: FranchiseGenre; label: string }[] = [
  { genre: "superherois", label: "Super-Heróis"      },
  { genre: "acao",        label: "Ação & Aventura"   },
  { genre: "scifi",       label: "Ficção Científica" },
  { genre: "fantasia",    label: "Fantasia & Magia"  },
  { genre: "terror",      label: "Terror & Suspense" },
  { genre: "drama",       label: "Drama & Crime"     },
  { genre: "animacao",    label: "Animação"          },
  { genre: "anime",       label: "Animes"            },
];
