export type FranchiseFetchType = "collection" | "search" | "tv";

export interface Franchise {
  id: string;
  name: string;
  shortName: string;
  emoji: string;
  tagline: string;
  description: string;
  color: string;
  accentColor: string;
  bgGradient: [string, string, string];
  category: "filmes" | "series" | "anime";
  fetchType: FranchiseFetchType;
  tmdbCollectionId?: number;
  tmdbTvId?: number;
  searchQuery?: string;
  yearRange: string;
  contentCount: number;
  totalHours: number;
  related: string[];
}

export const FRANCHISES: Franchise[] = [
  // ── FILMES ──────────────────────────────────────────────────
  {
    id: "marvel",
    name: "Marvel Studios",
    shortName: "Marvel",
    emoji: "🦸",
    tagline: "Universo Cinematográfico Marvel",
    description: "Todos os filmes e séries do MCU organizados cronologicamente. De Homem de Ferro a Vingadores, uma saga épica interconectada.",
    color: "#E23636",
    accentColor: "#FF4444",
    bgGradient: ["#1a0000", "#140a0a", "#0a0000"],
    category: "filmes",
    fetchType: "search",
    searchQuery: "marvel cinematic universe",
    yearRange: "2008 - Atual",
    contentCount: 35,
    totalHours: 120,
    related: ["dc", "xmen"],
  },
  {
    id: "dc",
    name: "DC Universe",
    shortName: "DC",
    emoji: "⚡",
    tagline: "DC Extended Universe",
    description: "O universo expandido da DC com Batman, Superman, Mulher-Maravilha, Liga da Justiça e muito mais.",
    color: "#0064FF",
    accentColor: "#4488FF",
    bgGradient: ["#000520", "#000a30", "#00031a"],
    category: "filmes",
    fetchType: "search",
    searchQuery: "DC Comics universe",
    yearRange: "2013 - Atual",
    contentCount: 22,
    totalHours: 75,
    related: ["marvel", "xmen"],
  },
  {
    id: "starwars",
    name: "Star Wars",
    shortName: "Star Wars",
    emoji: "🌌",
    tagline: "Que a Força esteja com você",
    description: "Uma galáxia muito, muito distante. Filmes, séries e especiais de uma das maiores sagas da história do cinema.",
    color: "#FFE81F",
    accentColor: "#FFD700",
    bgGradient: ["#0a0805", "#080600", "#050400"],
    category: "filmes",
    fetchType: "search",
    searchQuery: "Star Wars",
    yearRange: "1977 - Atual",
    contentCount: 18,
    totalHours: 45,
    related: ["marvel", "harrypotter"],
  },
  {
    id: "harrypotter",
    name: "Harry Potter",
    shortName: "Harry Potter",
    emoji: "⚡",
    tagline: "A saga de Hogwarts",
    description: "A saga completa do bruxinho mais famoso do mundo, do estudante de Hogwarts ao confronto final com Voldemort.",
    color: "#B8860B",
    accentColor: "#DAA520",
    bgGradient: ["#0d0800", "#100c00", "#080600"],
    category: "filmes",
    fetchType: "collection",
    tmdbCollectionId: 1241,
    yearRange: "2001 - 2011",
    contentCount: 8,
    totalHours: 19,
    related: ["fantasticbeasts", "lotr"],
  },
  {
    id: "fantasticbeasts",
    name: "Animais Fantásticos",
    shortName: "Animais Fantásticos",
    emoji: "🧙",
    tagline: "O mundo mágico antes de Harry",
    description: "A saga de Newt Scamander que expande o universo do mundo mágico décadas antes de Harry Potter.",
    color: "#7B5EA7",
    accentColor: "#9B7EC8",
    bgGradient: ["#0d0520", "#0a0318", "#060210"],
    category: "filmes",
    fetchType: "collection",
    tmdbCollectionId: 696374,
    yearRange: "2016 - 2022",
    contentCount: 3,
    totalHours: 7,
    related: ["harrypotter"],
  },
  {
    id: "lotr",
    name: "Senhor dos Anéis",
    shortName: "LOTR",
    emoji: "💍",
    tagline: "Uma jornada épica pela Terra-média",
    description: "A trilogia épica de J.R.R. Tolkien adaptada por Peter Jackson. Uma das maiores conquistas do cinema moderno.",
    color: "#8B7355",
    accentColor: "#C4A35A",
    bgGradient: ["#0a0800", "#100e00", "#080700"],
    category: "filmes",
    fetchType: "collection",
    tmdbCollectionId: 119,
    yearRange: "2001 - 2003",
    contentCount: 3,
    totalHours: 11,
    related: ["hobbit", "harrypotter"],
  },
  {
    id: "hobbit",
    name: "O Hobbit",
    shortName: "Hobbit",
    emoji: "🏔️",
    tagline: "Uma jornada inesperada",
    description: "A aventura de Bilbo Bolseiro e os anões em busca de recuperar a Montanha Solitária do dragão Smaug.",
    color: "#6B8E23",
    accentColor: "#8FBC3C",
    bgGradient: ["#050a00", "#080e00", "#040700"],
    category: "filmes",
    fetchType: "collection",
    tmdbCollectionId: 121938,
    yearRange: "2012 - 2014",
    contentCount: 3,
    totalHours: 9,
    related: ["lotr"],
  },
  {
    id: "jurassic",
    name: "Jurassic Park",
    shortName: "Jurassic",
    emoji: "🦕",
    tagline: "A vida encontra um caminho",
    description: "Dinossauros ressurgem no mundo moderno. Da ilha original ao mundo dominado por dinos, uma saga de sobrevivência.",
    color: "#228B22",
    accentColor: "#32CD32",
    bgGradient: ["#051005", "#081408", "#040a04"],
    category: "filmes",
    fetchType: "collection",
    tmdbCollectionId: 328,
    yearRange: "1993 - 2022",
    contentCount: 6,
    totalHours: 13,
    related: ["transformers"],
  },
  {
    id: "fastandfurious",
    name: "Velozes & Furiosos",
    shortName: "Velozes",
    emoji: "🚗",
    tagline: "Família acima de tudo",
    description: "A franquia mais veloz do cinema. De corridas de rua ao espaço, Dom Toretto e sua família não têm limites.",
    color: "#FF4500",
    accentColor: "#FF6347",
    bgGradient: ["#150500", "#1a0800", "#0a0300"],
    category: "filmes",
    fetchType: "collection",
    tmdbCollectionId: 9485,
    yearRange: "2001 - Atual",
    contentCount: 11,
    totalHours: 22,
    related: ["johnwick", "missionimpossible"],
  },
  {
    id: "missionimpossible",
    name: "Missão Impossível",
    shortName: "M:I",
    emoji: "🕵️",
    tagline: "Esta mensagem se autodestruirá",
    description: "Ethan Hunt e o IMF em missões impossíveis ao redor do mundo. Sequências de ação que definem o gênero.",
    color: "#DC143C",
    accentColor: "#FF1744",
    bgGradient: ["#150008", "#1a000a", "#0a0005"],
    category: "filmes",
    fetchType: "collection",
    tmdbCollectionId: 87359,
    yearRange: "1996 - Atual",
    contentCount: 8,
    totalHours: 16,
    related: ["johnwick", "jamesbond"],
  },
  {
    id: "johnwick",
    name: "John Wick",
    shortName: "John Wick",
    emoji: "🔫",
    tagline: "Ele voltou por um motivo",
    description: "O assassino mais letal do mundo. Quatro filmes de ação coreografada que revolucionaram o gênero.",
    color: "#FFD700",
    accentColor: "#FFA500",
    bgGradient: ["#0a0800", "#100e00", "#060500"],
    category: "filmes",
    fetchType: "collection",
    tmdbCollectionId: 404609,
    yearRange: "2014 - Atual",
    contentCount: 4,
    totalHours: 8,
    related: ["missionimpossible", "fastandfurious"],
  },
  {
    id: "transformers",
    name: "Transformers",
    shortName: "Transformers",
    emoji: "🤖",
    tagline: "Mais que atende os olhos",
    description: "Autobots contra Decepticons. Robôs gigantes em batalhas épicas pelo destino da humanidade.",
    color: "#FF8C00",
    accentColor: "#FFA500",
    bgGradient: ["#150800", "#1a0a00", "#0a0500"],
    category: "filmes",
    fetchType: "collection",
    tmdbCollectionId: 8650,
    yearRange: "2007 - Atual",
    contentCount: 7,
    totalHours: 14,
    related: ["jurassic"],
  },

  // ── SÉRIES ──────────────────────────────────────────────────
  {
    id: "walkingdead",
    name: "The Walking Dead",
    shortName: "TWD",
    emoji: "🧟",
    tagline: "Sobreviva ou vire zumbi",
    description: "O apocalipse zumbi que redefiniu as séries de terror. A luta de Rick Grimes e sobreviventes num mundo sem lei.",
    color: "#556B2F",
    accentColor: "#6B8E23",
    bgGradient: ["#080a04", "#0a0c05", "#060804"],
    category: "series",
    fetchType: "tv",
    tmdbTvId: 1402,
    yearRange: "2010 - 2022",
    contentCount: 11,
    totalHours: 165,
    related: ["theboys", "strangerthings"],
  },
  {
    id: "gameofthrones",
    name: "Game of Thrones",
    shortName: "GoT",
    emoji: "🐉",
    tagline: "Quando você joga o jogo dos tronos...",
    description: "A batalha pelo Trono de Ferro em Westeros. Intrigas, dragões e traições numa épica de fantasia medieval.",
    color: "#C0A060",
    accentColor: "#D4B870",
    bgGradient: ["#0d0a05", "#120e07", "#090705"],
    category: "series",
    fetchType: "tv",
    tmdbTvId: 1399,
    yearRange: "2011 - 2019",
    contentCount: 8,
    totalHours: 70,
    related: ["houseofdragon"],
  },
  {
    id: "houseofdragon",
    name: "House of the Dragon",
    shortName: "HotD",
    emoji: "🔥",
    tagline: "A dança dos dragões",
    description: "A guerra civil da Casa Targaryen 200 anos antes de Game of Thrones. Dragões, traição e poder absoluto.",
    color: "#C41E3A",
    accentColor: "#E83050",
    bgGradient: ["#1a0005", "#1a000a", "#0a0003"],
    category: "series",
    fetchType: "tv",
    tmdbTvId: 94997,
    yearRange: "2022 - Atual",
    contentCount: 2,
    totalHours: 20,
    related: ["gameofthrones"],
  },
  {
    id: "strangerthings",
    name: "Stranger Things",
    shortName: "Stranger Things",
    emoji: "👾",
    tagline: "O Mundo Invertido te chama",
    description: "Hawkins, Indiana, esconde um mundo paralelo sombrio. Crianças, adolescentes e o misterioso Mundo Invertido.",
    color: "#CC0000",
    accentColor: "#FF2222",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "series",
    fetchType: "tv",
    tmdbTvId: 66732,
    yearRange: "2016 - Atual",
    contentCount: 4,
    totalHours: 38,
    related: ["walkingdead", "theboys"],
  },
  {
    id: "theboys",
    name: "The Boys",
    shortName: "The Boys",
    emoji: "💥",
    tagline: "Super-heróis corrompidos pelo poder",
    description: "E se super-heróis fossem vilões? Billy Butcher e sua equipe contra o grupo de super-heróis mais poderoso e perigoso do mundo.",
    color: "#FF4500",
    accentColor: "#FF6600",
    bgGradient: ["#150500", "#180600", "#0a0300"],
    category: "series",
    fetchType: "tv",
    tmdbTvId: 76479,
    yearRange: "2019 - Atual",
    contentCount: 4,
    totalHours: 40,
    related: ["marvel", "strangerthings"],
  },

  // ── ANIMES ──────────────────────────────────────────────────
  {
    id: "dragonball",
    name: "Dragon Ball",
    shortName: "Dragon Ball",
    emoji: "🔮",
    tagline: "O poder dos Super Saiyajins",
    description: "Goku e seus amigos em batalhas épicas pelo universo. De criança buscando as esferas do dragão ao guerreiro mais poderoso do multiverso.",
    color: "#FF8C00",
    accentColor: "#FFA500",
    bgGradient: ["#150800", "#180a00", "#0a0500"],
    category: "anime",
    fetchType: "search",
    searchQuery: "Dragon Ball",
    yearRange: "1986 - Atual",
    contentCount: 8,
    totalHours: 600,
    related: ["naruto", "onepiece"],
  },
  {
    id: "naruto",
    name: "Naruto",
    shortName: "Naruto",
    emoji: "🍃",
    tagline: "Acredite no seu jeito ninja!",
    description: "A jornada de Naruto Uzumaki, do ninja rejeitado à Hokage da Vila da Folha. Uma saga épica de amizade e superação.",
    color: "#FF8C00",
    accentColor: "#FF6600",
    bgGradient: ["#150600", "#1a0800", "#0a0400"],
    category: "anime",
    fetchType: "search",
    searchQuery: "Naruto anime",
    yearRange: "2002 - 2017",
    contentCount: 3,
    totalHours: 720,
    related: ["dragonball", "onepiece", "bleach"],
  },
  {
    id: "onepiece",
    name: "One Piece",
    shortName: "One Piece",
    emoji: "⚓",
    tagline: "Vou ser o Rei dos Piratas!",
    description: "Monkey D. Luffy e sua tripulação navegam pelo Grand Line em busca do lendário tesouro One Piece. A maior aventura do mundo dos animes.",
    color: "#FF4500",
    accentColor: "#FF6347",
    bgGradient: ["#150300", "#1a0500", "#0a0200"],
    category: "anime",
    fetchType: "search",
    searchQuery: "One Piece anime",
    yearRange: "1999 - Atual",
    contentCount: 2,
    totalHours: 900,
    related: ["naruto", "dragonball"],
  },
  {
    id: "attackontitan",
    name: "Attack on Titan",
    shortName: "AoT",
    emoji: "⚔️",
    tagline: "A humanidade sob ataque",
    description: "Eren Yeager e o Batalhão de Reconhecimento lutam contra os Titãs. Uma das obras mais impactantes do anime moderno.",
    color: "#8B0000",
    accentColor: "#CC0000",
    bgGradient: ["#1a0000", "#140000", "#0a0000"],
    category: "anime",
    fetchType: "tv",
    tmdbTvId: 1429,
    yearRange: "2013 - 2023",
    contentCount: 4,
    totalHours: 40,
    related: ["naruto", "bleach"],
  },
  {
    id: "bleach",
    name: "Bleach",
    shortName: "Bleach",
    emoji: "🌙",
    tagline: "Soul Reaper mais poderoso",
    description: "Ichigo Kurosaki, um adolescente que se torna um Soul Reaper e defende o mundo dos espíritos dos Hollows.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000515", "#000820", "#00030f"],
    category: "anime",
    fetchType: "search",
    searchQuery: "Bleach anime",
    yearRange: "2004 - Atual",
    contentCount: 2,
    totalHours: 380,
    related: ["naruto", "attackontitan"],
  },
  {
    id: "pokemon",
    name: "Pokémon",
    shortName: "Pokémon",
    emoji: "⚡",
    tagline: "Gotta catch 'em all!",
    description: "Ash Ketchum e Pikachu embarcam em uma jornada para se tornarem Mestres Pokémon. O anime que marcou gerações.",
    color: "#FFD700",
    accentColor: "#FFCC00",
    bgGradient: ["#150f00", "#1a1200", "#0a0900"],
    category: "anime",
    fetchType: "search",
    searchQuery: "Pokemon anime",
    yearRange: "1997 - Atual",
    contentCount: 10,
    totalHours: 1200,
    related: ["dragonball", "naruto"],
  },
];

export const FEATURED_FRANCHISE = FRANCHISES.find((f) => f.id === "marvel")!;

export const FRANCHISE_BY_CATEGORY = {
  filmes: FRANCHISES.filter((f) => f.category === "filmes"),
  series: FRANCHISES.filter((f) => f.category === "series"),
  anime: FRANCHISES.filter((f) => f.category === "anime"),
};

export const getFranchise = (id: string) => FRANCHISES.find((f) => f.id === id);
