export type FranchiseFetchType = "collection" | "keyword" | "tv" | "search";
export type FranchiseGenre =
  | "superherois"
  | "acao"
  | "scifi"
  | "fantasia"
  | "terror"
  | "animacao"
  | "anime";
export type FranchiseCategory = "filmes" | "series" | "anime";

export interface ChronologicalItem {
  tmdbId: number;
  type: "movie" | "tv";
  label: string;
  note?: string;
}

export interface Franchise {
  id: string;
  name: string;
  shortName: string;
  tagline: string;
  description: string;
  color: string;
  accentColor: string;
  bgGradient: [string, string, string];
  category: FranchiseCategory;
  genre: FranchiseGenre;
  fetchType: FranchiseFetchType;
  tmdbCollectionId?: number;
  tmdbKeywordId?: number;
  tmdbTvId?: number;
  relatedTvIds?: number[];
  searchQuery?: string;
  searchType?: "movie" | "tv";
  yearRange: string;
  contentCount: number;
  totalHours: number;
  bannerFeatured?: boolean;
  isTop10?: boolean;
  related: string[];
  chronologicalContent?: ChronologicalItem[];
}

export const FRANCHISES: Franchise[] = [
  // ════════════════════════════════════════
  //  SUPER-HERÓIS
  // ════════════════════════════════════════
  {
    id: "marvel",
    name: "Marvel Studios",
    shortName: "Marvel",
    tagline: "Universo Cinematográfico Marvel",
    description:
      "Todos os filmes e séries do MCU — de Homem de Ferro a Vingadores, mais de 35 títulos interconectados em cinco Fases.",
    color: "#E23636",
    accentColor: "#FF4444",
    bgGradient: ["#1a0000", "#140a0a", "#0a0000"],
    category: "filmes",
    genre: "superherois",
    fetchType: "keyword",
    tmdbKeywordId: 180547,
    yearRange: "2008 - Atual",
    contentCount: 35,
    totalHours: 120,
    bannerFeatured: true,
    isTop10: true,
    related: ["dc", "xmen", "theboys"],
  },
  {
    id: "dc",
    name: "DC Universe",
    shortName: "DC",
    tagline: "DC Extended Universe",
    description:
      "Batman, Superman, Mulher-Maravilha e a Liga da Justiça protegem o mundo num universo épico de super-heróis.",
    color: "#0064FF",
    accentColor: "#4488FF",
    bgGradient: ["#000520", "#000a30", "#00031a"],
    category: "filmes",
    genre: "superherois",
    fetchType: "keyword",
    tmdbKeywordId: 310222,
    yearRange: "2013 - Atual",
    contentCount: 22,
    totalHours: 75,
    bannerFeatured: true,
    isTop10: true,
    related: ["marvel", "xmen"],
  },
  {
    id: "xmen",
    name: "X-Men",
    shortName: "X-Men",
    tagline: "Mutantes que defendem um mundo que os odeia",
    description:
      "A saga completa dos mutantes da Marvel — da escola do Professor Xavier ao confronto com Magneto.",
    color: "#FFD700",
    accentColor: "#FFEE44",
    bgGradient: ["#1a1200", "#151000", "#0a0800"],
    category: "filmes",
    genre: "superherois",
    fetchType: "collection",
    tmdbCollectionId: 748,
    yearRange: "2000 - Atual",
    contentCount: 13,
    totalHours: 27,
    related: ["marvel", "dc"],
  },
  {
    id: "theboys",
    name: "The Boys",
    shortName: "The Boys",
    tagline: "Super-heróis corrompidos pelo poder",
    description:
      "E se super-heróis fossem vilões? Billy Butcher e sua equipe enfrentam os Supes, o grupo de super-heróis mais perigoso.",
    color: "#FF4500",
    accentColor: "#FF6600",
    bgGradient: ["#150500", "#180600", "#0a0300"],
    category: "series",
    genre: "superherois",
    fetchType: "tv",
    tmdbTvId: 76479,
    yearRange: "2019 - Atual",
    contentCount: 4,
    totalHours: 40,
    bannerFeatured: true,
    isTop10: true,
    related: ["marvel", "strangerthings"],
  },

  // ════════════════════════════════════════
  //  AÇÃO & AVENTURA
  // ════════════════════════════════════════
  {
    id: "fastandfurious",
    name: "Velozes & Furiosos",
    shortName: "Velozes",
    tagline: "Família acima de tudo",
    description:
      "De corridas de rua ao espaço, Dom Toretto e sua família não têm limites. A franquia mais veloz do cinema.",
    color: "#FF4500",
    accentColor: "#FF6347",
    bgGradient: ["#150500", "#1a0800", "#0a0300"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 9485,
    yearRange: "2001 - Atual",
    contentCount: 11,
    totalHours: 22,
    bannerFeatured: true,
    related: ["johnwick", "missionimpossible"],
  },
  {
    id: "missionimpossible",
    name: "Missão Impossível",
    shortName: "M:I",
    tagline: "Esta mensagem se autodestruirá",
    description:
      "Ethan Hunt e o IMF em missões aparentemente impossíveis ao redor do mundo.",
    color: "#DC143C",
    accentColor: "#FF1744",
    bgGradient: ["#150008", "#1a000a", "#0a0005"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 87359,
    yearRange: "1996 - Atual",
    contentCount: 8,
    totalHours: 16,
    related: ["johnwick", "fastandfurious"],
  },
  {
    id: "johnwick",
    name: "John Wick",
    shortName: "John Wick",
    tagline: "Ele voltou por um motivo",
    description:
      "O assassino mais letal do mundo. Quatro filmes de ação coreografada que revolucionaram o gênero.",
    color: "#FFD700",
    accentColor: "#FFA500",
    bgGradient: ["#0a0800", "#100e00", "#060500"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 404609,
    yearRange: "2014 - Atual",
    contentCount: 4,
    totalHours: 8,
    related: ["missionimpossible", "fastandfurious"],
  },
  {
    id: "indianajones",
    name: "Indiana Jones",
    shortName: "Indiana Jones",
    tagline: "O maior arqueólogo-aventureiro",
    description:
      "Dr. Henry Jones Jr. e suas aventuras arqueológicas ao redor do mundo em busca de artefatos lendários.",
    color: "#C8A96E",
    accentColor: "#E8C97E",
    bgGradient: ["#100c04", "#150f06", "#0a0803"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 84,
    yearRange: "1981 - 2023",
    contentCount: 5,
    totalHours: 11,
    related: ["fastandfurious", "missionimpossible"],
  },
  {
    id: "bourne",
    name: "Jason Bourne",
    shortName: "Bourne",
    tagline: "Quem sou eu? O que fiz?",
    description:
      "Jason Bourne, agente da CIA sem memória, descobre os segredos sombrios de seu passado enquanto foge.",
    color: "#6688AA",
    accentColor: "#88AACC",
    bgGradient: ["#060810", "#080a16", "#040610"],
    category: "filmes",
    genre: "acao",
    fetchType: "collection",
    tmdbCollectionId: 31562,
    yearRange: "2002 - 2016",
    contentCount: 5,
    totalHours: 10,
    related: ["missionimpossible", "johnwick"],
  },

  // ════════════════════════════════════════
  //  FICÇÃO CIENTÍFICA
  // ════════════════════════════════════════
  {
    id: "starwars",
    name: "Star Wars",
    shortName: "Star Wars",
    tagline: "Que a Força esteja com você",
    description:
      "Uma galáxia muito, muito distante. A saga Skywalker, spinoffs e séries Disney+ numa das maiores sagas do cinema.",
    color: "#FFE81F",
    accentColor: "#FFD700",
    bgGradient: ["#0a0805", "#080600", "#050400"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 10,
    relatedTvIds: [82856, 115036, 92830, 83867, 114461],
    yearRange: "1977 - Atual",
    contentCount: 18,
    totalHours: 45,
    bannerFeatured: true,
    isTop10: true,
    related: ["marvel", "alien"],
    chronologicalContent: [
      { tmdbId: 1893, type: "movie", label: "Ep. I — A Ameaça Fantasma", note: "32 ABY" },
      { tmdbId: 1894, type: "movie", label: "Ep. II — Ataque dos Clones", note: "22 ABY" },
      { tmdbId: 1895, type: "movie", label: "Ep. III — A Vingança dos Sith", note: "19 ABY" },
      { tmdbId: 348350, type: "movie", label: "Solo: Uma História Star Wars", note: "10 ABY" },
      { tmdbId: 92830, type: "tv", label: "Obi-Wan Kenobi (série)", note: "9 ABY" },
      { tmdbId: 83867, type: "tv", label: "Andor (série)", note: "5 ABY" },
      { tmdbId: 330459, type: "movie", label: "Rogue One", note: "0 ABY" },
      { tmdbId: 11, type: "movie", label: "Ep. IV — Uma Nova Esperança", note: "0 DBY" },
      { tmdbId: 1891, type: "movie", label: "Ep. V — O Império Contra-Ataca", note: "3 DBY" },
      { tmdbId: 1892, type: "movie", label: "Ep. VI — O Retorno de Jedi", note: "4 DBY" },
      { tmdbId: 82856, type: "tv", label: "The Mandalorian (série)", note: "9 DBY" },
      { tmdbId: 115036, type: "tv", label: "Livro de Boba Fett (série)", note: "9 DBY" },
      { tmdbId: 114461, type: "tv", label: "Ahsoka (série)", note: "9 DBY" },
      { tmdbId: 140607, type: "movie", label: "Ep. VII — O Despertar da Força", note: "34 DBY" },
      { tmdbId: 181808, type: "movie", label: "Ep. VIII — Os Últimos Jedi", note: "34 DBY" },
      { tmdbId: 181812, type: "movie", label: "Ep. IX — A Ascensão Skywalker", note: "35 DBY" },
    ],
  },
  {
    id: "matrix",
    name: "Matrix",
    shortName: "Matrix",
    tagline: "A verdade está lá fora",
    description:
      "Neo descobre que a realidade é uma simulação e lidera a rebelião humana contra as máquinas.",
    color: "#00FF41",
    accentColor: "#33FF66",
    bgGradient: ["#001400", "#001800", "#000e00"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 2344,
    yearRange: "1999 - 2021",
    contentCount: 4,
    totalHours: 9,
    related: ["terminator", "alien"],
  },
  {
    id: "alien",
    name: "Alien",
    shortName: "Alien",
    tagline: "No espaço ninguém pode ouvir você gritar",
    description:
      "A criatura mais aterrorizante do cinema. A saga completa de Ripley contra os Xenomorfos.",
    color: "#AACC55",
    accentColor: "#BBDD66",
    bgGradient: ["#080e02", "#0a1204", "#060a02"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 8091,
    yearRange: "1979 - Atual",
    contentCount: 7,
    totalHours: 14,
    related: ["starwars", "terminator"],
  },
  {
    id: "terminator",
    name: "O Exterminador",
    shortName: "Terminator",
    tagline: "I'll be back",
    description:
      "Máquinas do futuro viajam no tempo para eliminar John Connor. A saga de resistência humana contra Skynet.",
    color: "#CC2200",
    accentColor: "#FF3311",
    bgGradient: ["#1a0600", "#1a0400", "#0a0200"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 528,
    yearRange: "1984 - Atual",
    contentCount: 6,
    totalHours: 12,
    related: ["alien", "matrix"],
  },
  {
    id: "jurassic",
    name: "Jurassic Park",
    shortName: "Jurassic",
    tagline: "A vida encontra um caminho",
    description:
      "Dinossauros ressurgem no mundo moderno. Da ilha original ao mundo dominado por dinos.",
    color: "#228B22",
    accentColor: "#32CD32",
    bgGradient: ["#051005", "#081408", "#040a04"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 328,
    yearRange: "1993 - 2022",
    contentCount: 6,
    totalHours: 13,
    related: ["alien", "terminator"],
  },
  {
    id: "strangerthings",
    name: "Stranger Things",
    shortName: "Stranger Things",
    tagline: "O Mundo Invertido te chama",
    description:
      "Hawkins, Indiana, esconde um mundo paralelo sombrio. Crianças e adolescentes enfrentam o misterioso Mundo Invertido.",
    color: "#CC0000",
    accentColor: "#FF2222",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "series",
    genre: "scifi",
    fetchType: "tv",
    tmdbTvId: 66732,
    yearRange: "2016 - Atual",
    contentCount: 4,
    totalHours: 38,
    bannerFeatured: true,
    isTop10: true,
    related: ["walkingdead", "theboys"],
  },
  {
    id: "transformers",
    name: "Transformers",
    shortName: "Transformers",
    tagline: "Mais que atende os olhos",
    description:
      "Autobots contra Decepticons. Robôs gigantes em batalhas épicas pelo destino da humanidade.",
    color: "#FF8C00",
    accentColor: "#FFA500",
    bgGradient: ["#150800", "#1a0a00", "#0a0500"],
    category: "filmes",
    genre: "scifi",
    fetchType: "collection",
    tmdbCollectionId: 8650,
    yearRange: "2007 - Atual",
    contentCount: 7,
    totalHours: 14,
    related: ["alien", "matrix"],
  },

  // ════════════════════════════════════════
  //  FANTASIA & MAGIA
  // ════════════════════════════════════════
  {
    id: "harrypotter",
    name: "Harry Potter",
    shortName: "Harry Potter",
    tagline: "A saga de Hogwarts",
    description:
      "A saga completa do bruxinho mais famoso do mundo, de Hogwarts ao confronto final com Voldemort.",
    color: "#B8860B",
    accentColor: "#DAA520",
    bgGradient: ["#0d0800", "#100c00", "#080600"],
    category: "filmes",
    genre: "fantasia",
    fetchType: "collection",
    tmdbCollectionId: 1241,
    yearRange: "2001 - 2011",
    contentCount: 8,
    totalHours: 19,
    bannerFeatured: true,
    isTop10: true,
    related: ["fantasticbeasts", "lotr"],
    chronologicalContent: [
      { tmdbId: 671, type: "movie", label: "A Pedra Filosofal", note: "Ano 1" },
      { tmdbId: 672, type: "movie", label: "A Câmara Secreta", note: "Ano 2" },
      { tmdbId: 673, type: "movie", label: "O Prisioneiro de Azkaban", note: "Ano 3" },
      { tmdbId: 674, type: "movie", label: "O Cálice de Fogo", note: "Ano 4" },
      { tmdbId: 675, type: "movie", label: "A Ordem da Fênix", note: "Ano 5" },
      { tmdbId: 767, type: "movie", label: "O Enigma do Príncipe", note: "Ano 6" },
      { tmdbId: 12444, type: "movie", label: "Relíquias da Morte — Parte 1", note: "Ano 7" },
      { tmdbId: 12445, type: "movie", label: "Relíquias da Morte — Parte 2", note: "Ano 7" },
    ],
  },
  {
    id: "fantasticbeasts",
    name: "Animais Fantásticos",
    shortName: "Animais Fantásticos",
    tagline: "O mundo mágico antes de Harry",
    description:
      "A saga de Newt Scamander que expande o universo do mundo mágico décadas antes de Harry Potter.",
    color: "#7B5EA7",
    accentColor: "#9B7EC8",
    bgGradient: ["#0d0520", "#0a0318", "#060210"],
    category: "filmes",
    genre: "fantasia",
    fetchType: "search",
    searchQuery: "Fantastic Beasts",
    searchType: "movie",
    yearRange: "2016 - 2022",
    contentCount: 3,
    totalHours: 7,
    related: ["harrypotter"],
  },
  {
    id: "lotr",
    name: "Senhor dos Anéis",
    shortName: "LOTR",
    tagline: "Uma jornada épica pela Terra-média",
    description:
      "A trilogia épica de J.R.R. Tolkien adaptada por Peter Jackson. Uma das maiores conquistas do cinema moderno.",
    color: "#8B7355",
    accentColor: "#C4A35A",
    bgGradient: ["#0a0800", "#100e00", "#080700"],
    category: "filmes",
    genre: "fantasia",
    fetchType: "collection",
    tmdbCollectionId: 119,
    yearRange: "2001 - 2003",
    contentCount: 3,
    totalHours: 11,
    bannerFeatured: true,
    isTop10: true,
    related: ["hobbit", "harrypotter"],
    chronologicalContent: [
      { tmdbId: 120, type: "movie", label: "A Sociedade do Anel", note: "Parte 1" },
      { tmdbId: 121, type: "movie", label: "As Duas Torres", note: "Parte 2" },
      { tmdbId: 122, type: "movie", label: "O Retorno do Rei", note: "Parte 3" },
    ],
  },
  {
    id: "hobbit",
    name: "O Hobbit",
    shortName: "Hobbit",
    tagline: "Uma jornada inesperada",
    description:
      "A aventura de Bilbo Bolseiro e os anões em busca de recuperar a Montanha Solitária do dragão Smaug.",
    color: "#6B8E23",
    accentColor: "#8FBC3C",
    bgGradient: ["#050a00", "#080e00", "#040700"],
    category: "filmes",
    genre: "fantasia",
    fetchType: "collection",
    tmdbCollectionId: 121938,
    yearRange: "2012 - 2014",
    contentCount: 3,
    totalHours: 9,
    related: ["lotr"],
  },
  {
    id: "gameofthrones",
    name: "Game of Thrones",
    shortName: "GoT",
    tagline: "Quando você joga o jogo dos tronos...",
    description:
      "A batalha pelo Trono de Ferro em Westeros. Intrigas, dragões e traições numa épica de fantasia medieval.",
    color: "#C0A060",
    accentColor: "#D4B870",
    bgGradient: ["#0d0a05", "#120e07", "#090705"],
    category: "series",
    genre: "fantasia",
    fetchType: "tv",
    tmdbTvId: 1399,
    relatedTvIds: [94997],
    yearRange: "2011 - 2019",
    contentCount: 8,
    totalHours: 70,
    bannerFeatured: true,
    isTop10: true,
    related: ["houseofdragon"],
  },
  {
    id: "houseofdragon",
    name: "House of the Dragon",
    shortName: "HotD",
    tagline: "A dança dos dragões",
    description:
      "A guerra civil da Casa Targaryen 200 anos antes de Game of Thrones.",
    color: "#C41E3A",
    accentColor: "#E83050",
    bgGradient: ["#1a0005", "#1a000a", "#0a0003"],
    category: "series",
    genre: "fantasia",
    fetchType: "tv",
    tmdbTvId: 94997,
    relatedTvIds: [1399],
    yearRange: "2022 - Atual",
    contentCount: 2,
    totalHours: 20,
    related: ["gameofthrones"],
  },

  // ════════════════════════════════════════
  //  TERROR & SUSPENSE
  // ════════════════════════════════════════
  {
    id: "walkingdead",
    name: "The Walking Dead",
    shortName: "TWD",
    tagline: "Sobreviva ou vire zumbi",
    description:
      "O apocalipse zumbi que redefiniu as séries de terror. A luta de sobreviventes num mundo sem lei.",
    color: "#556B2F",
    accentColor: "#6B8E23",
    bgGradient: ["#080a04", "#0a0c05", "#060804"],
    category: "series",
    genre: "terror",
    fetchType: "tv",
    tmdbTvId: 1402,
    relatedTvIds: [62286],
    yearRange: "2010 - 2022",
    contentCount: 11,
    totalHours: 165,
    bannerFeatured: true,
    related: ["theboys", "strangerthings"],
  },
  {
    id: "conjuring",
    name: "Universo Conjuring",
    shortName: "Conjuring",
    tagline: "Baseado em casos reais de horror",
    description:
      "Os detetives paranormais Ed e Lorraine Warren, Annabelle, a Freira e o Homem Torto. O universo de terror mais assustador.",
    color: "#8B0000",
    accentColor: "#CC1111",
    bgGradient: ["#1a0000", "#150000", "#0a0000"],
    category: "filmes",
    genre: "terror",
    fetchType: "keyword",
    tmdbKeywordId: 256599,
    yearRange: "2013 - Atual",
    contentCount: 8,
    totalHours: 16,
    related: ["walkingdead"],
  },
  {
    id: "it",
    name: "IT — A Coisa",
    shortName: "IT",
    tagline: "Eles flutuam lá embaixo",
    description:
      "Pennywise, o palhaço dançante, aterroriza Derry há séculos. A adaptação mais assustadora de Stephen King.",
    color: "#CC0000",
    accentColor: "#FF2222",
    bgGradient: ["#1a0000", "#140000", "#0a0000"],
    category: "filmes",
    genre: "terror",
    fetchType: "search",
    searchQuery: "IT Chapter",
    searchType: "movie",
    yearRange: "2017 - 2019",
    contentCount: 2,
    totalHours: 5,
    related: ["conjuring", "walkingdead"],
  },

  // ════════════════════════════════════════
  //  ANIMAÇÃO
  // ════════════════════════════════════════
  {
    id: "toystory",
    name: "Toy Story",
    shortName: "Toy Story",
    tagline: "Para o infinito e além!",
    description:
      "Woody, Buzz e os brinquedos de Andy numa saga emocionante de amizade, aventura e crescimento.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000820", "#000a28", "#000510"],
    category: "filmes",
    genre: "animacao",
    fetchType: "collection",
    tmdbCollectionId: 10194,
    yearRange: "1995 - 2019",
    contentCount: 4,
    totalHours: 6,
    related: ["shrek", "kungfupanda"],
  },
  {
    id: "shrek",
    name: "Shrek",
    shortName: "Shrek",
    tagline: "Estava tudo errado e deu tudo certo",
    description:
      "O ogro mais amado do cinema e seu fiel companheiro Burro em aventuras pelo reino de Far Far Away.",
    color: "#558B2F",
    accentColor: "#76C442",
    bgGradient: ["#061006", "#081408", "#040a04"],
    category: "filmes",
    genre: "animacao",
    fetchType: "collection",
    tmdbCollectionId: 230,
    yearRange: "2001 - Atual",
    contentCount: 5,
    totalHours: 8,
    related: ["toystory", "kungfupanda"],
  },
  {
    id: "kungfupanda",
    name: "Kung Fu Panda",
    shortName: "Kung Fu Panda",
    tagline: "Não existe segredo na sopa secreta",
    description:
      "Po, o panda desajeitado que se torna o Guerreiro Dragão e defende o Vale da Paz com kung fu incrível.",
    color: "#CC6600",
    accentColor: "#FF8822",
    bgGradient: ["#150800", "#1a0a00", "#0a0500"],
    category: "filmes",
    genre: "animacao",
    fetchType: "collection",
    tmdbCollectionId: 77816,
    yearRange: "2008 - Atual",
    contentCount: 4,
    totalHours: 7,
    related: ["shrek", "toystory"],
  },

  // ════════════════════════════════════════
  //  ANIMES
  // ════════════════════════════════════════
  {
    id: "dragonball",
    name: "Dragon Ball",
    shortName: "Dragon Ball",
    tagline: "O poder dos Super Saiyajins",
    description:
      "Goku e seus amigos em batalhas épicas pelo universo. Da infância ao guerreiro mais poderoso do multiverso.",
    color: "#FF8C00",
    accentColor: "#FFA500",
    bgGradient: ["#150800", "#180a00", "#0a0500"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 12609,
    relatedTvIds: [39230, 60554],
    yearRange: "1986 - Atual",
    contentCount: 8,
    totalHours: 600,
    bannerFeatured: true,
    isTop10: true,
    related: ["naruto", "onepiece"],
  },
  {
    id: "naruto",
    name: "Naruto",
    shortName: "Naruto",
    tagline: "Acredite no seu jeito ninja!",
    description:
      "A jornada de Naruto Uzumaki, do ninja rejeitado à Hokage da Vila da Folha.",
    color: "#FF8C00",
    accentColor: "#FF6600",
    bgGradient: ["#150600", "#1a0800", "#0a0400"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 46260,
    relatedTvIds: [31910],
    yearRange: "2002 - 2017",
    contentCount: 3,
    totalHours: 720,
    isTop10: true,
    related: ["dragonball", "onepiece", "bleach"],
  },
  {
    id: "onepiece",
    name: "One Piece",
    shortName: "One Piece",
    tagline: "Vou ser o Rei dos Piratas!",
    description:
      "Monkey D. Luffy navega pelo Grand Line em busca do lendário tesouro One Piece.",
    color: "#FF4500",
    accentColor: "#FF6347",
    bgGradient: ["#150300", "#1a0500", "#0a0200"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 37854,
    relatedTvIds: [228979],
    yearRange: "1999 - Atual",
    contentCount: 2,
    totalHours: 900,
    related: ["naruto", "dragonball"],
  },
  {
    id: "attackontitan",
    name: "Attack on Titan",
    shortName: "AoT",
    tagline: "A humanidade sob ataque",
    description:
      "Eren Yeager e o Batalhão de Reconhecimento lutam contra os Titãs. Uma das obras mais impactantes do anime moderno.",
    color: "#8B0000",
    accentColor: "#CC0000",
    bgGradient: ["#1a0000", "#140000", "#0a0000"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 1429,
    yearRange: "2013 - 2023",
    contentCount: 4,
    totalHours: 40,
    bannerFeatured: true,
    related: ["naruto", "bleach"],
  },
  {
    id: "bleach",
    name: "Bleach",
    shortName: "Bleach",
    tagline: "Soul Reaper mais poderoso",
    description:
      "Ichigo Kurosaki, adolescente que se torna Soul Reaper e defende o mundo dos espíritos.",
    color: "#4169E1",
    accentColor: "#6688FF",
    bgGradient: ["#000515", "#000820", "#00030f"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 46261,
    yearRange: "2004 - Atual",
    contentCount: 2,
    totalHours: 380,
    related: ["naruto", "attackontitan"],
  },
  {
    id: "pokemon",
    name: "Pokémon",
    shortName: "Pokémon",
    tagline: "Gotta catch 'em all!",
    description:
      "Ash Ketchum e Pikachu embarcam em uma jornada para se tornarem Mestres Pokémon.",
    color: "#FFD700",
    accentColor: "#FFCC00",
    bgGradient: ["#150f00", "#1a1200", "#0a0900"],
    category: "anime",
    genre: "anime",
    fetchType: "tv",
    tmdbTvId: 60572,
    yearRange: "1997 - Atual",
    contentCount: 10,
    totalHours: 1200,
    related: ["dragonball", "naruto"],
  },
];

// ── Helpers ───────────────────────────────────────────────────
export const BANNER_FRANCHISES = FRANCHISES.filter((f) => f.bannerFeatured);
export const TOP10_FRANCHISES = FRANCHISES.filter((f) => f.isTop10);
export const FEATURED_FRANCHISE = FRANCHISES.find((f) => f.id === "marvel")!;
export const getFranchise = (id: string) => FRANCHISES.find((f) => f.id === id);

export const GENRE_SECTIONS: { genre: FranchiseGenre; label: string; emoji: string }[] = [
  { genre: "superherois", label: "Super-Heróis", emoji: "🦸" },
  { genre: "acao",        label: "Ação & Aventura", emoji: "💥" },
  { genre: "scifi",       label: "Ficção Científica", emoji: "🚀" },
  { genre: "fantasia",    label: "Fantasia & Magia", emoji: "✨" },
  { genre: "terror",      label: "Terror & Suspense", emoji: "👻" },
  { genre: "animacao",    label: "Animação", emoji: "🎨" },
  { genre: "anime",       label: "Animes", emoji: "⛩️" },
];
