export interface StreamingPlatform {
  id: string;
  name: string;
  tmdbId: number | null;
  logoPath: string | null;
  brandColor: string;
  bgColor: string;
  bgGradient: [string, string, string];
  accentColor: string;
  textColor: string;
  category: "main" | "specific" | "niche";
  tagline?: string;
}

export const STREAMING_PLATFORMS: StreamingPlatform[] = [
  // ── Gerais ─────────────────────────────────────────────────
  {
    id: "netflix",
    name: "Netflix",
    tmdbId: 8,
    logoPath: "/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg",
    brandColor: "#E50914",
    bgColor: "#141414",
    bgGradient: ["#1a0000", "#141414", "#0a0000"],
    accentColor: "#E50914",
    textColor: "#FFFFFF",
    category: "main",
    tagline: "Séries, Filmes e muito mais",
  },
  {
    id: "prime",
    name: "Prime Video",
    tmdbId: 119,
    logoPath: "/emthp39XA2YScoYL1p0sdbAH2WA.jpg",
    brandColor: "#00A8E1",
    bgColor: "#0F171E",
    bgGradient: ["#0F171E", "#16202c", "#0a1018"],
    accentColor: "#00A8E1",
    textColor: "#FFFFFF",
    category: "main",
    tagline: "Filmes e Séries Originais",
  },
  {
    id: "disney",
    name: "Disney+",
    tmdbId: 337,
    logoPath: "/7rwgEs15tFwyR9NPQ5vpzxTj19Q.jpg",
    brandColor: "#0063E5",
    bgColor: "#040714",
    bgGradient: ["#040714", "#060d22", "#03060f"],
    accentColor: "#F9CE33",
    textColor: "#FFFFFF",
    category: "main",
    tagline: "Disney, Marvel, Star Wars e mais",
  },
  {
    id: "max",
    name: "Max",
    tmdbId: 1899,
    logoPath: "/Ajqyt5ilvtD2N3HlrPaJdWl9UHD.jpg",
    brandColor: "#002BE7",
    bgColor: "#000E42",
    bgGradient: ["#000E42", "#000c38", "#00062a"],
    accentColor: "#00B4FF",
    textColor: "#FFFFFF",
    category: "main",
    tagline: "HBO, Warner e muito mais",
  },
  {
    id: "apple",
    name: "Apple TV+",
    tmdbId: 350,
    logoPath: "/6uhKBfmtzFqOcLousHwZuzcrScK.jpg",
    brandColor: "#FFFFFF",
    bgColor: "#000000",
    bgGradient: ["#0a0a0a", "#000000", "#050505"],
    accentColor: "#FFFFFF",
    textColor: "#FFFFFF",
    category: "main",
    tagline: "Originais Apple",
  },
  {
    id: "globoplay",
    name: "Globoplay",
    tmdbId: 307,
    logoPath: null,
    brandColor: "#FF5A00",
    bgColor: "#0a0a0a",
    bgGradient: ["#1a0900", "#0a0a0a", "#000000"],
    accentColor: "#FF5A00",
    textColor: "#FFFFFF",
    category: "main",
    tagline: "Globo, Séries e Novelas",
  },

  // ── Específicos / Cineastas ─────────────────────────────────
  {
    id: "paramount",
    name: "Paramount+",
    tmdbId: 531,
    logoPath: "/fi83B1oztoS47xxcemFdPMhIzK.jpg",
    brandColor: "#0064FF",
    bgColor: "#00013E",
    bgGradient: ["#00013E", "#000530", "#000220"],
    accentColor: "#0064FF",
    textColor: "#FFFFFF",
    category: "specific",
    tagline: "A Montanha Chama você",
  },
  {
    id: "mubi",
    name: "MUBI",
    tmdbId: 11,
    logoPath: "/t2yyOv40HZeVlLjYsCsPHnWLk4W.jpg",
    brandColor: "#FF4B27",
    bgColor: "#1B1B1B",
    bgGradient: ["#1B1B1B", "#111111", "#0d0d0d"],
    accentColor: "#FF4B27",
    textColor: "#FFFFFF",
    category: "specific",
    tagline: "Cinema de Autor",
  },
  {
    id: "telecine",
    name: "Telecine Play",
    tmdbId: 155,
    logoPath: null,
    brandColor: "#FFB600",
    bgColor: "#0d0d1a",
    bgGradient: ["#0d0d1a", "#0a0a14", "#060610"],
    accentColor: "#FFB600",
    textColor: "#FFFFFF",
    category: "specific",
    tagline: "Grandes Estreias do Cinema",
  },
  {
    id: "looke",
    name: "Looke",
    tmdbId: 47,
    logoPath: null,
    brandColor: "#00B4FF",
    bgColor: "#001832",
    bgGradient: ["#001832", "#001428", "#000e1e"],
    accentColor: "#00B4FF",
    textColor: "#FFFFFF",
    category: "specific",
    tagline: "Cinema Nacional e Internacional",
  },
  {
    id: "universal",
    name: "Universal+",
    tmdbId: 685,
    logoPath: null,
    brandColor: "#EB3C00",
    bgColor: "#0A0A0A",
    bgGradient: ["#1a0800", "#0A0A0A", "#000000"],
    accentColor: "#EB3C00",
    textColor: "#FFFFFF",
    category: "specific",
    tagline: "Séries Internacionais",
  },
  {
    id: "imovision",
    name: "Reserva Imovision",
    tmdbId: null,
    logoPath: null,
    brandColor: "#C8973B",
    bgColor: "#1A1206",
    bgGradient: ["#1A1206", "#120e04", "#0a0802"],
    accentColor: "#C8973B",
    textColor: "#FFFFFF",
    category: "specific",
    tagline: "Cinema de Arte e Autor",
  },

  // ── Nicho / Esporte ─────────────────────────────────────────
  {
    id: "crunchyroll",
    name: "Crunchyroll",
    tmdbId: 283,
    logoPath: "/8Gt1iClBlzTeQs8WQm8UrCoIRnQ.jpg",
    brandColor: "#FF6500",
    bgColor: "#0d0505",
    bgGradient: ["#1a0500", "#0d0505", "#050000"],
    accentColor: "#FF6500",
    textColor: "#FFFFFF",
    category: "niche",
    tagline: "O Maior Catálogo de Animes",
  },
  {
    id: "premiere",
    name: "Premiere",
    tmdbId: null,
    logoPath: null,
    brandColor: "#E21C35",
    bgColor: "#060606",
    bgGradient: ["#1a0008", "#060606", "#000000"],
    accentColor: "#E21C35",
    textColor: "#FFFFFF",
    category: "niche",
    tagline: "Futebol Brasileiro ao Vivo",
  },
  {
    id: "nba",
    name: "NBA League Pass",
    tmdbId: null,
    logoPath: null,
    brandColor: "#1D428A",
    bgColor: "#040C18",
    bgGradient: ["#040C18", "#030a14", "#020810"],
    accentColor: "#C9982D",
    textColor: "#FFFFFF",
    category: "niche",
    tagline: "Basquete ao Vivo",
  },
  {
    id: "ufc",
    name: "UFC Fight Pass",
    tmdbId: null,
    logoPath: null,
    brandColor: "#D20A0A",
    bgColor: "#0a0000",
    bgGradient: ["#1a0000", "#0a0000", "#050000"],
    accentColor: "#D20A0A",
    textColor: "#FFFFFF",
    category: "niche",
    tagline: "MMA e Artes Marciais",
  },
  {
    id: "luminetv",
    name: "Lumine TV",
    tmdbId: null,
    logoPath: null,
    brandColor: "#9B59B6",
    bgColor: "#0F0015",
    bgGradient: ["#150020", "#0F0015", "#08000e"],
    accentColor: "#B366CC",
    textColor: "#FFFFFF",
    category: "niche",
    tagline: "Entretenimento Premium",
  },
  {
    id: "brasilparalelo",
    name: "Brasil Paralelo",
    tmdbId: null,
    logoPath: null,
    brandColor: "#2C5F2E",
    bgColor: "#0A1400",
    bgGradient: ["#0A1400", "#081000", "#050c00"],
    accentColor: "#4CAF50",
    textColor: "#FFFFFF",
    category: "niche",
    tagline: "Documentários Brasileiros",
  },
];

export const MAIN_PLATFORMS = STREAMING_PLATFORMS.filter((p) => p.category === "main");
export const SPECIFIC_PLATFORMS = STREAMING_PLATFORMS.filter((p) => p.category === "specific");
export const NICHE_PLATFORMS = STREAMING_PLATFORMS.filter((p) => p.category === "niche");

export const getPlatform = (id: string) => STREAMING_PLATFORMS.find((p) => p.id === id);
