export interface StreamingPlatform {
  id: string;
  name: string;
  tmdbId: number | null;
  logoPath: string | null;
  logoUrl?: string;
  brandColor: string;
  bgColor: string;
  bgGradient: [string, string, string];
  accentColor: string;
  textColor: string;
  category: "main" | "specific" | "niche";
  tagline?: string;
}

export const STREAMING_PLATFORMS: StreamingPlatform[] = [
  // ── Gerais ─────────────────────────────────────────────────
  {
    id: "netflix",
    name: "Netflix",
    tmdbId: 8,
    logoPath: "/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg",
    logoUrl: "https://logospng.org/download/netflix/logo-netflix-1024.png",
    brandColor: "#E50914",
    bgColor: "#1a0a0a",
    bgGradient: ["#4a0008", "#1f0004", "#0d0002"],
    accentColor: "#E50914",
    textColor: "#FFFFFF",
    category: "main",
    tagline: "PREMIUM",
  },
  {
    id: "prime",
    name: "Prime Video",
    tmdbId: 119,
    logoPath: "/emthp39XA2YScoYL1p0sdbAH2WA.jpg",
    logoUrl: "https://logospng.org/download/prime-video/logo-prime-video-1024.png",
    brandColor: "#00A8E1",
    bgColor: "#0c1820",
    bgGradient: ["#062840", "#0d1e30", "#060f1a"],
    accentColor: "#00A8E1",
    textColor: "#FFFFFF",
    category: "main",
    tagline: "PREMIUM",
  },
  {
    id: "disney",
    name: "Disney+",
    tmdbId: 337,
    logoPath: "/7rwgEs15tFwyR9NPQ5vpzxTj19Q.jpg",
    logoUrl: "https://logospng.org/download/disneyplus/logo-disneyplus-1024.png",
    brandColor: "#1a6fff",
    bgColor: "#04071a",
    bgGradient: ["#041a50", "#050f30", "#030818"],
    accentColor: "#F9CE33",
    textColor: "#FFFFFF",
    category: "main",
    tagline: "PREMIUM",
  },
  {
    id: "max",
    name: "Max",
    tmdbId: 1899,
    logoPath: "/Ajqyt5ilvtD2N3HlrPaJdWl9UHD.jpg",
    logoUrl: "https://logospng.org/download/hbo-max/hbo-max-256.png",
    brandColor: "#5B5EFF",
    bgColor: "#07083a",
    bgGradient: ["#0c0e60", "#080b48", "#040630"],
    accentColor: "#00B4FF",
    textColor: "#FFFFFF",
    category: "main",
    tagline: "PREMIUM",
  },
  {
    id: "apple",
    name: "Apple TV+",
    tmdbId: 350,
    logoPath: "/6uhKBfmtzFqOcLousHwZuzcrScK.jpg",
    logoUrl: "https://logospng.org/download/apple-tv/apple-tv-256.png",
    brandColor: "#FFFFFF",
    bgColor: "#111111",
    bgGradient: ["#222222", "#161616", "#0a0a0a"],
    accentColor: "#FFFFFF",
    textColor: "#FFFFFF",
    category: "main",
    tagline: "PREMIUM",
  },
  {
    id: "globoplay",
    name: "Globoplay",
    tmdbId: 307,
    logoPath: null,
    logoUrl: "https://logospng.org/download/globoplay/logo-globoplay-1024.png",
    brandColor: "#FF5A00",
    bgColor: "#150800",
    bgGradient: ["#3d1400", "#220900", "#0f0400"],
    accentColor: "#FF5A00",
    textColor: "#FFFFFF",
    category: "main",
    tagline: "PREMIUM",
  },

  // ── Específicos / Cineastas ─────────────────────────────────
  {
    id: "paramount",
    name: "Paramount+",
    tmdbId: 531,
    logoPath: "/fi83B1oztoS47xxcemFdPMhIzK.jpg",
    brandColor: "#0064FF",
    bgColor: "#00013E",
    bgGradient: ["#00065a", "#000440", "#000228"],
    accentColor: "#0064FF",
    textColor: "#FFFFFF",
    category: "specific",
    tagline: "A Montanha Chama você",
  },
  {
    id: "mubi",
    name: "MUBI",
    tmdbId: 11,
    logoPath: "/t2yyOv40HZeVlLjYsCsPHnWLk4W.jpg",
    brandColor: "#FF4B27",
    bgColor: "#1B1B1B",
    bgGradient: ["#3a1008", "#221008", "#120808"],
    accentColor: "#FF4B27",
    textColor: "#FFFFFF",
    category: "specific",
    tagline: "Cinema de Autor",
  },
  {
    id: "telecine",
    name: "Telecine Play",
    tmdbId: 155,
    logoPath: null,
    logoUrl: "https://logospng.org/download/telecine/logo-telecine-1024.png",
    brandColor: "#FFB600",
    bgColor: "#0d0d1a",
    bgGradient: ["#261c00", "#181200", "#0c0900"],
    accentColor: "#FFB600",
    textColor: "#FFFFFF",
    category: "specific",
    tagline: "Grandes Estreias do Cinema",
  },
  {
    id: "looke",
    name: "Looke",
    tmdbId: 47,
    logoPath: null,
    brandColor: "#00B4FF",
    bgColor: "#001832",
    bgGradient: ["#002a48", "#001e34", "#001020"],
    accentColor: "#00B4FF",
    textColor: "#FFFFFF",
    category: "specific",
    tagline: "Cinema Nacional e Internacional",
  },
  {
    id: "universal",
    name: "Universal+",
    tmdbId: 685,
    logoPath: null,
    brandColor: "#EB3C00",
    bgColor: "#0A0A0A",
    bgGradient: ["#3a0e00", "#200800", "#0d0400"],
    accentColor: "#EB3C00",
    textColor: "#FFFFFF",
    category: "specific",
    tagline: "Séries Internacionais",
  },
  {
    id: "imovision",
    name: "Reserva Imovision",
    tmdbId: null,
    logoPath: null,
    brandColor: "#C8973B",
    bgColor: "#1A1206",
    bgGradient: ["#2e2000", "#1e1400", "#100a00"],
    accentColor: "#C8973B",
    textColor: "#FFFFFF",
    category: "specific",
    tagline: "Cinema de Arte e Autor",
  },

  // ── Nicho / Esporte ─────────────────────────────────────────
  {
    id: "crunchyroll",
    name: "Crunchyroll",
    tmdbId: 283,
    logoPath: "/8Gt1iClBlzTeQs8WQm8UrCoIRnQ.jpg",
    brandColor: "#FF6500",
    bgColor: "#120800",
    bgGradient: ["#3a1400", "#220a00", "#100400"],
    accentColor: "#FF6500",
    textColor: "#FFFFFF",
    category: "niche",
    tagline: "O Maior Catálogo de Animes",
  },
  {
    id: "premiere",
    name: "Premiere",
    tmdbId: null,
    logoPath: null,
    brandColor: "#E21C35",
    bgColor: "#060606",
    bgGradient: ["#380010", "#1e0008", "#0a0003"],
    accentColor: "#E21C35",
    textColor: "#FFFFFF",
    category: "niche",
    tagline: "Futebol Brasileiro ao Vivo",
  },
  {
    id: "nba",
    name: "NBA League Pass",
    tmdbId: null,
    logoPath: null,
    brandColor: "#1D428A",
    bgColor: "#040C18",
    bgGradient: ["#061840", "#040f28", "#020810"],
    accentColor: "#C9982D",
    textColor: "#FFFFFF",
    category: "niche",
    tagline: "Basquete ao Vivo",
  },
  {
    id: "ufc",
    name: "UFC Fight Pass",
    tmdbId: null,
    logoPath: null,
    brandColor: "#D20A0A",
    bgColor: "#0a0000",
    bgGradient: ["#3d0000", "#1f0000", "#0a0000"],
    accentColor: "#D20A0A",
    textColor: "#FFFFFF",
    category: "niche",
    tagline: "MMA e Artes Marciais",
  },
  {
    id: "luminetv",
    name: "Lumine TV",
    tmdbId: null,
    logoPath: null,
    brandColor: "#9B59B6",
    bgColor: "#0F0015",
    bgGradient: ["#280040", "#180028", "#0a0018"],
    accentColor: "#B366CC",
    textColor: "#FFFFFF",
    category: "niche",
    tagline: "Entretenimento Premium",
  },
  {
    id: "brasilparalelo",
    name: "Brasil Paralelo",
    tmdbId: null,
    logoPath: null,
    brandColor: "#2C5F2E",
    bgColor: "#0A1400",
    bgGradient: ["#0a2000", "#071600", "#040e00"],
    accentColor: "#4CAF50",
    textColor: "#FFFFFF",
    category: "niche",
    tagline: "Documentários Brasileiros",
  },
];

export const MAIN_PLATFORMS = STREAMING_PLATFORMS.filter((p) => p.category === "main");
export const SPECIFIC_PLATFORMS = STREAMING_PLATFORMS.filter((p) => p.category === "specific");
export const NICHE_PLATFORMS = STREAMING_PLATFORMS.filter((p) => p.category === "niche");

export const getPlatform = (id: string) => STREAMING_PLATFORMS.find((p) => p.id === id);
