// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/EmailPreview.tsx": () => import("../components/mockups/EmailPreview.tsx"),
  "./components/mockups/channels/HomeAoVivo.tsx": () => import("../components/mockups/channels/HomeAoVivo.tsx"),
  "./components/mockups/channels/PlayerPremium.tsx": () => import("../components/mockups/channels/PlayerPremium.tsx"),
  "./components/mockups/channels/SinopseCinematica.tsx": () => import("../components/mockups/channels/SinopseCinematica.tsx"),
  "./components/mockups/sting/StingPreview.tsx": () => import("../components/mockups/sting/StingPreview.tsx"),
  "./components/mockups/vinheta/VinhetaNetplay.tsx": () => import("../components/mockups/vinheta/VinhetaNetplay.tsx")
};
